import type { TaskRow } from "./types";

export const taskFixtures: TaskRow[] = [
	{
		id: "t1",
		title: "Painting hall",
		priority: "high",
		peopleNeeded: 2,
		room: "Hall",
		status: "ready",
		assignedTo: [],
	},
	{
		id: "t2",
		title: "Pack kitchen boxes",
		priority: "high",
		peopleNeeded: 3,
		room: "Kitchen",
		status: "ready",
		assignedTo: ["Alice"],
	},
	{
		id: "t3",
		title: "Disassemble bed frames",
		priority: "medium",
		peopleNeeded: 2,
		room: "Bedroom",
		status: "ready",
		assignedTo: [],
	},
	{
		id: "t4",
		title: "Move living room furniture",
		priority: "medium",
		peopleNeeded: 4,
		room: "Living Room",
		status: "ready",
		assignedTo: ["Bob", "Carol"],
	},
	{
		id: "t5",
		title: "Clean bathroom tiles",
		priority: "low",
		peopleNeeded: 1,
		room: "Bathroom",
		status: "ready",
		assignedTo: [],
	},
	{
		id: "t6",
		title: "Label fragile boxes",
		priority: "low",
		peopleNeeded: 1,
		room: "Garage",
		status: "ready",
		assignedTo: ["Alice", "Bob"],
	},
];
