FROM golang:1.26.2-alpine AS build

WORKDIR /app

COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 go build -o backend .

FROM alpine:latest

WORKDIR /app
COPY --from=build /app/backend .

EXPOSE 8080

CMD ["./backend"]
