// This file is auto-generated by @hey-api/openapi-ts

export { getHello, type Options } from './sdk.gen';
export type { ClientOptions, ErrorDetail, ErrorModel, ErrorModelWritable, GetHelloData, GetHelloError, GetHelloErrors, GetHelloResponse, GetHelloResponses, HelloOutputBody, HelloOutputBodyWritable } from './types.gen';
