// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetDashboardDailyScheduleData, GetDashboardDailyScheduleErrors, GetDashboardDailyScheduleResponses, GetDashboardPeopleAvailabilityData, GetDashboardPeopleAvailabilityErrors, GetDashboardPeopleAvailabilityResponses, GetHelloData, GetHelloErrors, GetHelloResponses, GetPlanningWindowData, GetPlanningWindowErrors, GetPlanningWindowResponses, GetTasksBacklogData, GetTasksBacklogErrors, GetTasksBacklogResponses, PutPlanningWindowData, PutPlanningWindowErrors, PutPlanningWindowResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Daily schedule for the dashboard
 *
 * Returns a dashboard-ready daily schedule read model with date columns, available-helper counts, and ordered schedule task cards. The start parameter defaults to the planning-window start date (2026-07-05); clients should pass start explicitly for a different window.
 */
export const getDashboardDailySchedule = <ThrowOnError extends boolean = false>(options?: Options<GetDashboardDailyScheduleData, ThrowOnError>): RequestResult<GetDashboardDailyScheduleResponses, GetDashboardDailyScheduleErrors, ThrowOnError> => (options?.client ?? client).get<GetDashboardDailyScheduleResponses, GetDashboardDailyScheduleErrors, ThrowOnError>({ url: '/api/dashboard/daily-schedule', ...options });

/**
 * People availability for the dashboard
 *
 * Returns a combined payload with date-range metadata, summary counts, per-person daily availability, and a status legend. The start parameter defaults to the server-local current date; clients should pass start explicitly for timezone-correct results. availableToday counts only people whose status on selectedDate equals 'available'.
 */
export const getDashboardPeopleAvailability = <ThrowOnError extends boolean = false>(options?: Options<GetDashboardPeopleAvailabilityData, ThrowOnError>): RequestResult<GetDashboardPeopleAvailabilityResponses, GetDashboardPeopleAvailabilityErrors, ThrowOnError> => (options?.client ?? client).get<GetDashboardPeopleAvailabilityResponses, GetDashboardPeopleAvailabilityErrors, ThrowOnError>({ url: '/api/dashboard/people-availability', ...options });

/**
 * Hello world
 *
 * Returns a hello-world message confirming the backend is reachable.
 */
export const getHello = <ThrowOnError extends boolean = false>(options?: Options<GetHelloData, ThrowOnError>): RequestResult<GetHelloResponses, GetHelloErrors, ThrowOnError> => (options?.client ?? client).get<GetHelloResponses, GetHelloErrors, ThrowOnError>({ url: '/api/hello', ...options });

/**
 * Global planning window
 *
 * Returns the global move range with startDate, endDate, and inclusive day count. The planning window is the canonical source of truth for the move timeline. All date-dependent views derive their rendered content from this contract.
 */
export const getPlanningWindow = <ThrowOnError extends boolean = false>(options?: Options<GetPlanningWindowData, ThrowOnError>): RequestResult<GetPlanningWindowResponses, GetPlanningWindowErrors, ThrowOnError> => (options?.client ?? client).get<GetPlanningWindowResponses, GetPlanningWindowErrors, ThrowOnError>({ url: '/api/planning-window', ...options });

/**
 * Update planning window
 *
 * Updates the planning window start and end dates. Both dates are required and endDate must be >= startDate. Returns the updated planning window with recalculated inclusive day count.
 */
export const putPlanningWindow = <ThrowOnError extends boolean = false>(options: Options<PutPlanningWindowData, ThrowOnError>): RequestResult<PutPlanningWindowResponses, PutPlanningWindowErrors, ThrowOnError> => (options.client ?? client).put<PutPlanningWindowResponses, PutPlanningWindowErrors, ThrowOnError>({
    url: '/api/planning-window',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Task backlog data
 *
 * Returns a combined payload with derived summary counts, task backlog rows, a canonical priority legend, and a canonical task-status legend. The endpoint serves as the read-only source of truth for backlog task data used by the dashboard and /tasks route.
 */
export const getTasksBacklog = <ThrowOnError extends boolean = false>(options?: Options<GetTasksBacklogData, ThrowOnError>): RequestResult<GetTasksBacklogResponses, GetTasksBacklogErrors, ThrowOnError> => (options?.client ?? client).get<GetTasksBacklogResponses, GetTasksBacklogErrors, ThrowOnError>({ url: '/api/tasks/backlog', ...options });
