// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ClearToolBringerData, ClearToolBringerErrors, ClearToolBringerResponses, CreatePersonData, CreatePersonErrors, CreatePersonResponses, CreateRoomData, CreateRoomErrors, CreateRoomResponses, CreateScheduleCardData, CreateScheduleCardErrors, CreateScheduleCardResponses, CreateTaskData, CreateTaskErrors, CreateTaskResponses, CreateToolData, CreateToolErrors, CreateToolResponses, DeletePersonAvailabilityData, DeletePersonAvailabilityErrors, DeletePersonAvailabilityResponses, DeletePersonData, DeletePersonErrors, DeletePersonResponses, DeleteRoomData, DeleteRoomErrors, DeleteRoomResponses, DeleteScheduleCardData, DeleteScheduleCardErrors, DeleteScheduleCardResponses, DeleteTaskData, DeleteTaskErrors, DeleteTaskResponses, DeleteToolData, DeleteToolErrors, DeleteToolResponses, GetDashboardDailyScheduleData, GetDashboardDailyScheduleErrors, GetDashboardDailyScheduleResponses, GetDashboardPeopleAvailabilityData, GetDashboardPeopleAvailabilityErrors, GetDashboardPeopleAvailabilityResponses, GetHelloData, GetHelloErrors, GetHelloResponses, GetPlanningWindowData, GetPlanningWindowErrors, GetPlanningWindowResponses, GetTasksBacklogData, GetTasksBacklogErrors, GetTasksBacklogResponses, GetToolsData, GetToolsErrors, GetToolsResponses, ListRoomsData, ListRoomsErrors, ListRoomsResponses, PutPlanningWindowData, PutPlanningWindowErrors, PutPlanningWindowResponses, SetToolBringerData, SetToolBringerErrors, SetToolBringerResponses, UpdatePersonData, UpdatePersonErrors, UpdatePersonResponses, UpdateRoomData, UpdateRoomErrors, UpdateRoomResponses, UpdateScheduleCardData, UpdateScheduleCardErrors, UpdateScheduleCardResponses, UpdateTaskData, UpdateTaskErrors, UpdateTaskResponses, UpdateToolData, UpdateToolErrors, UpdateToolResponses, UpsertPersonAvailabilityData, UpsertPersonAvailabilityErrors, UpsertPersonAvailabilityResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Daily schedule for the dashboard
 *
 * Returns a dashboard-ready daily schedule read model with date columns, available-helper counts, and ordered schedule task cards. The start parameter defaults to the planning-window start date (2026-07-05); clients should pass start explicitly for a different window.
 */
export const getDashboardDailySchedule = <ThrowOnError extends boolean = false>(options?: Options<GetDashboardDailyScheduleData, ThrowOnError>): RequestResult<GetDashboardDailyScheduleResponses, GetDashboardDailyScheduleErrors, ThrowOnError> => (options?.client ?? client).get<GetDashboardDailyScheduleResponses, GetDashboardDailyScheduleErrors, ThrowOnError>({ url: '/api/dashboard/daily-schedule', ...options });

/**
 * People availability for the dashboard
 *
 * Returns a combined payload with date-range metadata, summary counts, per-person daily availability, and a status legend. The start parameter defaults to the planning-window start date; clients should pass start explicitly for timezone-correct results. availableToday counts only people whose status on selectedDate equals 'available'.
 */
export const getDashboardPeopleAvailability = <ThrowOnError extends boolean = false>(options?: Options<GetDashboardPeopleAvailabilityData, ThrowOnError>): RequestResult<GetDashboardPeopleAvailabilityResponses, GetDashboardPeopleAvailabilityErrors, ThrowOnError> => (options?.client ?? client).get<GetDashboardPeopleAvailabilityResponses, GetDashboardPeopleAvailabilityErrors, ThrowOnError>({ url: '/api/dashboard/people-availability', ...options });

/**
 * Hello world
 *
 * Returns a hello-world message confirming the backend is reachable.
 */
export const getHello = <ThrowOnError extends boolean = false>(options?: Options<GetHelloData, ThrowOnError>): RequestResult<GetHelloResponses, GetHelloErrors, ThrowOnError> => (options?.client ?? client).get<GetHelloResponses, GetHelloErrors, ThrowOnError>({ url: '/api/hello', ...options });

/**
 * Create a person
 *
 * Creates a new person with a server-assigned sequential ID.
 */
export const createPerson = <ThrowOnError extends boolean = false>(options: Options<CreatePersonData, ThrowOnError>): RequestResult<CreatePersonResponses, CreatePersonErrors, ThrowOnError> => (options.client ?? client).post<CreatePersonResponses, CreatePersonErrors, ThrowOnError>({
    url: '/api/people',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a person
 *
 * Deletes a person. Returns 409 Conflict if the person is referenced by backlog or schedule assignments.
 */
export const deletePerson = <ThrowOnError extends boolean = false>(options: Options<DeletePersonData, ThrowOnError>): RequestResult<DeletePersonResponses, DeletePersonErrors, ThrowOnError> => (options.client ?? client).delete<DeletePersonResponses, DeletePersonErrors, ThrowOnError>({ url: '/api/people/{id}', ...options });

/**
 * Update a person
 *
 * Updates the name and initials of an existing person.
 */
export const updatePerson = <ThrowOnError extends boolean = false>(options: Options<UpdatePersonData, ThrowOnError>): RequestResult<UpdatePersonResponses, UpdatePersonErrors, ThrowOnError> => (options.client ?? client).put<UpdatePersonResponses, UpdatePersonErrors, ThrowOnError>({
    url: '/api/people/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete person availability for a date
 *
 * Deletes a single availability entry for a person on a specific date. Idempotent: deleting an already-absent entry succeeds without error. Subsequent dashboard reads will fall back to the default-missing-availability behavior.
 */
export const deletePersonAvailability = <ThrowOnError extends boolean = false>(options: Options<DeletePersonAvailabilityData, ThrowOnError>): RequestResult<DeletePersonAvailabilityResponses, DeletePersonAvailabilityErrors, ThrowOnError> => (options.client ?? client).delete<DeletePersonAvailabilityResponses, DeletePersonAvailabilityErrors, ThrowOnError>({ url: '/api/people/{id}/availability/{date}', ...options });

/**
 * Upsert person availability for a date
 *
 * Creates or updates a single availability entry for a person on a specific date. The status must be one of: available, busy, partial, off. The date must be within the planning window.
 */
export const upsertPersonAvailability = <ThrowOnError extends boolean = false>(options: Options<UpsertPersonAvailabilityData, ThrowOnError>): RequestResult<UpsertPersonAvailabilityResponses, UpsertPersonAvailabilityErrors, ThrowOnError> => (options.client ?? client).put<UpsertPersonAvailabilityResponses, UpsertPersonAvailabilityErrors, ThrowOnError>({
    url: '/api/people/{id}/availability/{date}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Global planning window
 *
 * Returns the global move range with startDate, endDate, and inclusive day count. The planning window is the canonical source of truth for the move timeline. All date-dependent views derive their rendered content from this contract.
 */
export const getPlanningWindow = <ThrowOnError extends boolean = false>(options?: Options<GetPlanningWindowData, ThrowOnError>): RequestResult<GetPlanningWindowResponses, GetPlanningWindowErrors, ThrowOnError> => (options?.client ?? client).get<GetPlanningWindowResponses, GetPlanningWindowErrors, ThrowOnError>({ url: '/api/planning-window', ...options });

/**
 * Update planning window
 *
 * Updates the planning window start and end dates. Both dates are required and endDate must be >= startDate. Returns the updated planning window with recalculated inclusive day count.
 */
export const putPlanningWindow = <ThrowOnError extends boolean = false>(options: Options<PutPlanningWindowData, ThrowOnError>): RequestResult<PutPlanningWindowResponses, PutPlanningWindowErrors, ThrowOnError> => (options.client ?? client).put<PutPlanningWindowResponses, PutPlanningWindowErrors, ThrowOnError>({
    url: '/api/planning-window',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List rooms and areas
 *
 * Returns all room and area records ordered by name.
 */
export const listRooms = <ThrowOnError extends boolean = false>(options?: Options<ListRoomsData, ThrowOnError>): RequestResult<ListRoomsResponses, ListRoomsErrors, ThrowOnError> => (options?.client ?? client).get<ListRoomsResponses, ListRoomsErrors, ThrowOnError>({ url: '/api/rooms', ...options });

/**
 * Create a room or area
 *
 * Creates a new room or area record and returns it.
 */
export const createRoom = <ThrowOnError extends boolean = false>(options: Options<CreateRoomData, ThrowOnError>): RequestResult<CreateRoomResponses, CreateRoomErrors, ThrowOnError> => (options.client ?? client).post<CreateRoomResponses, CreateRoomErrors, ThrowOnError>({
    url: '/api/rooms',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a room or area
 *
 * Deletes a room or area record by ID. Returns 404 if the ID is not found.
 */
export const deleteRoom = <ThrowOnError extends boolean = false>(options: Options<DeleteRoomData, ThrowOnError>): RequestResult<DeleteRoomResponses, DeleteRoomErrors, ThrowOnError> => (options.client ?? client).delete<DeleteRoomResponses, DeleteRoomErrors, ThrowOnError>({ url: '/api/rooms/{id}', ...options });

/**
 * Update a room or area
 *
 * Updates an existing room or area record by ID. Returns 404 if the ID is not found.
 */
export const updateRoom = <ThrowOnError extends boolean = false>(options: Options<UpdateRoomData, ThrowOnError>): RequestResult<UpdateRoomResponses, UpdateRoomErrors, ThrowOnError> => (options.client ?? client).put<UpdateRoomResponses, UpdateRoomErrors, ThrowOnError>({
    url: '/api/rooms/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create a schedule card
 *
 * Creates a new schedule card with server-assigned sched-* ID. Returns 400 for invalid input or out-of-window date.
 */
export const createScheduleCard = <ThrowOnError extends boolean = false>(options: Options<CreateScheduleCardData, ThrowOnError>): RequestResult<CreateScheduleCardResponses, CreateScheduleCardErrors, ThrowOnError> => (options.client ?? client).post<CreateScheduleCardResponses, CreateScheduleCardErrors, ThrowOnError>({
    url: '/api/schedule/cards',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a schedule card
 *
 * Deletes a schedule card and its assignments transactionally. Returns 404 if the card ID is unknown.
 */
export const deleteScheduleCard = <ThrowOnError extends boolean = false>(options: Options<DeleteScheduleCardData, ThrowOnError>): RequestResult<DeleteScheduleCardResponses, DeleteScheduleCardErrors, ThrowOnError> => (options.client ?? client).delete<DeleteScheduleCardResponses, DeleteScheduleCardErrors, ThrowOnError>({ url: '/api/schedule/cards/{id}', ...options });

/**
 * Update a schedule card
 *
 * Updates a schedule card and replaces assignments transactionally. Returns 400 for validation errors, 404 if the card ID is unknown.
 */
export const updateScheduleCard = <ThrowOnError extends boolean = false>(options: Options<UpdateScheduleCardData, ThrowOnError>): RequestResult<UpdateScheduleCardResponses, UpdateScheduleCardErrors, ThrowOnError> => (options.client ?? client).put<UpdateScheduleCardResponses, UpdateScheduleCardErrors, ThrowOnError>({
    url: '/api/schedule/cards/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create a backlog task
 *
 * Creates a new backlog task with server-assigned task-* ID and append sort order. Returns 400 for invalid priority, status, empty title, peopleNeeded < 1, missing room, or unknown assigned person IDs.
 */
export const createTask = <ThrowOnError extends boolean = false>(options: Options<CreateTaskData, ThrowOnError>): RequestResult<CreateTaskResponses, CreateTaskErrors, ThrowOnError> => (options.client ?? client).post<CreateTaskResponses, CreateTaskErrors, ThrowOnError>({
    url: '/api/tasks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Task backlog data
 *
 * Returns a combined payload with derived summary counts, task backlog rows, a canonical priority legend, and a canonical task-status legend. The endpoint serves as the read-only source of truth for backlog task data used by the dashboard and /tasks route.
 */
export const getTasksBacklog = <ThrowOnError extends boolean = false>(options?: Options<GetTasksBacklogData, ThrowOnError>): RequestResult<GetTasksBacklogResponses, GetTasksBacklogErrors, ThrowOnError> => (options?.client ?? client).get<GetTasksBacklogResponses, GetTasksBacklogErrors, ThrowOnError>({ url: '/api/tasks/backlog', ...options });

/**
 * Delete a backlog task
 *
 * Deletes a backlog task and its assignments transactionally. Returns 404 if the task ID is unknown.
 */
export const deleteTask = <ThrowOnError extends boolean = false>(options: Options<DeleteTaskData, ThrowOnError>): RequestResult<DeleteTaskResponses, DeleteTaskErrors, ThrowOnError> => (options.client ?? client).delete<DeleteTaskResponses, DeleteTaskErrors, ThrowOnError>({ url: '/api/tasks/{id}', ...options });

/**
 * Update a backlog task
 *
 * Updates a backlog task and replaces assignments transactionally. Returns 400 for validation errors, 404 if the task ID is unknown.
 */
export const updateTask = <ThrowOnError extends boolean = false>(options: Options<UpdateTaskData, ThrowOnError>): RequestResult<UpdateTaskResponses, UpdateTaskErrors, ThrowOnError> => (options.client ?? client).put<UpdateTaskResponses, UpdateTaskErrors, ThrowOnError>({
    url: '/api/tasks/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Tool list with coverage summary
 *
 * Returns all tools ordered by sort order plus a derived coverage summary (total, claimed, open). A tool is claimed (crossed off) when it has a bringer and open when it has none.
 */
export const getTools = <ThrowOnError extends boolean = false>(options?: Options<GetToolsData, ThrowOnError>): RequestResult<GetToolsResponses, GetToolsErrors, ThrowOnError> => (options?.client ?? client).get<GetToolsResponses, GetToolsErrors, ThrowOnError>({ url: '/api/tools', ...options });

/**
 * Create a tool
 *
 * Creates a new tool with a server-assigned tool-* ID and append sort order, with no bringer. Returns 400 for an empty name.
 */
export const createTool = <ThrowOnError extends boolean = false>(options: Options<CreateToolData, ThrowOnError>): RequestResult<CreateToolResponses, CreateToolErrors, ThrowOnError> => (options.client ?? client).post<CreateToolResponses, CreateToolErrors, ThrowOnError>({
    url: '/api/tools',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a tool
 *
 * Deletes a tool. Returns 404 if the tool ID is unknown.
 */
export const deleteTool = <ThrowOnError extends boolean = false>(options: Options<DeleteToolData, ThrowOnError>): RequestResult<DeleteToolResponses, DeleteToolErrors, ThrowOnError> => (options.client ?? client).delete<DeleteToolResponses, DeleteToolErrors, ThrowOnError>({ url: '/api/tools/{id}', ...options });

/**
 * Update a tool
 *
 * Updates a tool's name and sort order. Returns 400 for an empty name, 404 if the tool ID is unknown.
 */
export const updateTool = <ThrowOnError extends boolean = false>(options: Options<UpdateToolData, ThrowOnError>): RequestResult<UpdateToolResponses, UpdateToolErrors, ThrowOnError> => (options.client ?? client).put<UpdateToolResponses, UpdateToolErrors, ThrowOnError>({
    url: '/api/tools/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Unclaim a tool
 *
 * Clears the tool's bringer, returning it to open. Idempotent: clearing an already-open tool succeeds. Returns 404 for an unknown tool.
 */
export const clearToolBringer = <ThrowOnError extends boolean = false>(options: Options<ClearToolBringerData, ThrowOnError>): RequestResult<ClearToolBringerResponses, ClearToolBringerErrors, ThrowOnError> => (options.client ?? client).delete<ClearToolBringerResponses, ClearToolBringerErrors, ThrowOnError>({ url: '/api/tools/{id}/bringer', ...options });

/**
 * Claim a tool
 *
 * Sets the tool's bringer, replacing any existing one. Claiming does not depend on the person's availability. Returns 404 for an unknown tool and 400 for an unknown person.
 */
export const setToolBringer = <ThrowOnError extends boolean = false>(options: Options<SetToolBringerData, ThrowOnError>): RequestResult<SetToolBringerResponses, SetToolBringerErrors, ThrowOnError> => (options.client ?? client).put<SetToolBringerResponses, SetToolBringerErrors, ThrowOnError>({
    url: '/api/tools/{id}/bringer',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
