// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AssignedPerson = {
    /**
     * Stable person key
     */
    id: string;
    /**
     * Initials
     */
    initials: string;
    /**
     * Full name
     */
    name: string;
};

export type AvailabilityEntry = {
    /**
     * Date in ISO 8601 format (YYYY-MM-DD)
     */
    date: string;
    /**
     * One of: available, busy, partial, off
     */
    status: string;
};

export type CreatePersonInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Client-supplied stable person key (slug)
     */
    id: string;
    /**
     * Initials
     */
    initials: string;
    /**
     * Full name
     */
    name: string;
};

export type CreateRoomRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Human-readable room or area name
     */
    name: string;
    /**
     * One of: room, area
     */
    type: 'room' | 'area';
};

export type CreateTaskRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Person-ID strings for assigned helpers, may be empty
     */
    assignedTo: Array<string> | null;
    /**
     * Number of people required for the task, minimum 1
     */
    peopleNeeded: number;
    /**
     * One of: high, medium, low
     */
    priority: 'high' | 'medium' | 'low';
    /**
     * Room or area the task belongs to
     */
    room: string;
    /**
     * One of: backlog, ready, assigned
     */
    status: 'backlog' | 'ready' | 'assigned';
    /**
     * Human-readable task description
     */
    title: string;
};

export type DailyScheduleBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * One entry per date in the requested window
     */
    days: Array<ScheduleDay> | null;
    /**
     * Date range metadata
     */
    range: ScheduleRange;
};

export type DashboardBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * People with daily availability
     */
    people: Array<Person> | null;
    /**
     * Date range metadata
     */
    range: Range;
    /**
     * Canonical status legend
     */
    statuses: Array<StatusLegend> | null;
    /**
     * Summary counts
     */
    summary: Summary;
};

export type DeleteAvailabilityOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
};

export type DeletePersonOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type HelloOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
};

export type ListRoomsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * All room/area records
     */
    rooms: Array<Room> | null;
};

export type Person = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * One entry per date in the range
     */
    availability: Array<AvailabilityEntry> | null;
    /**
     * Stable person key
     */
    id: string;
    /**
     * Initials
     */
    initials: string;
    /**
     * Full name
     */
    name: string;
};

export type PlanningWindowBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Inclusive day count between startDate and endDate
     */
    days: number;
    /**
     * End date of the planning window (ISO 8601)
     */
    endDate: string;
    /**
     * Start date of the planning window (ISO 8601)
     */
    startDate: string;
};

export type PriorityLegend = {
    /**
     * Design system color intent
     */
    colorIntent: string;
    /**
     * Priority identifier
     */
    id: string;
    /**
     * Human-readable label
     */
    label: string;
};

export type Range = {
    /**
     * Number of dates in the window (inclusive of startDate)
     */
    days: number;
    /**
     * End date of the window (ISO 8601)
     */
    endDate: string;
    /**
     * Reference date for summary counts (equals startDate)
     */
    selectedDate: string;
    /**
     * Start date of the window (ISO 8601)
     */
    startDate: string;
};

export type Room = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * ISO 8601 timestamp of creation
     */
    createdAt: string;
    /**
     * Stable room identifier, prefixed 'room-'
     */
    id: string;
    /**
     * Human-readable room or area name
     */
    name: string;
    /**
     * One of: room, area
     */
    type: 'room' | 'area';
    /**
     * ISO 8601 timestamp of last update
     */
    updatedAt: string;
};

export type ScheduleDay = {
    /**
     * Number of people available on this date
     */
    availablePeopleCount: number;
    /**
     * Date in ISO 8601 format (YYYY-MM-DD)
     */
    date: string;
    /**
     * Human-readable day header
     */
    label: string;
    /**
     * Ordered schedule task cards
     */
    tasks: Array<TaskCard> | null;
};

export type ScheduleRange = {
    /**
     * Number of dates in the window (inclusive of startDate)
     */
    days: number;
    /**
     * End date of the window (ISO 8601)
     */
    endDate: string;
    /**
     * Start date of the window (ISO 8601)
     */
    startDate: string;
};

export type StatusLegend = {
    /**
     * Design system color intent
     */
    colorIntent: string;
    /**
     * Status identifier
     */
    id: string;
    /**
     * Human-readable label
     */
    label: string;
};

export type Summary = {
    /**
     * Number of people with status 'available' on selectedDate
     */
    availableToday: number;
    /**
     * Total number of people in the response
     */
    totalPeople: number;
};

export type TaskBacklogBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Canonical priority legend
     */
    priorities: Array<PriorityLegend> | null;
    /**
     * Canonical task-status legend
     */
    statuses: Array<TaskStatusLegend> | null;
    /**
     * Derived summary counts
     */
    summary: TaskSummary;
    /**
     * Backlog task rows
     */
    tasks: Array<TaskRow> | null;
};

export type TaskCard = {
    /**
     * Number of people currently assigned (derived from assignedPeople)
     */
    assignedCount: number;
    /**
     * People assigned to this task
     */
    assignedPeople: Array<AssignedPerson> | null;
    /**
     * Stable task identifier
     */
    id: string;
    /**
     * Number of people needed for the task (>=1)
     */
    peopleNeeded: number;
    /**
     * One of: high, medium, low
     */
    priority: string;
    /**
     * Room or area name
     */
    roomArea: string;
    /**
     * One of: fullyStaffed, underStaffed
     */
    staffingStatus: string;
    /**
     * Task title
     */
    title: string;
};

export type TaskRow = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Person-ID strings for assigned helpers, may be empty
     */
    assignedTo: Array<string> | null;
    /**
     * Stable task identifier, prefixed 'task-'
     */
    id: string;
    /**
     * Number of people required for the task, minimum 1
     */
    peopleNeeded: number;
    /**
     * One of: high, medium, low
     */
    priority: string;
    /**
     * Room or area the task belongs to
     */
    room: string;
    /**
     * One of: backlog, ready, assigned
     */
    status: string;
    /**
     * Human-readable task description
     */
    title: string;
};

export type TaskStatusLegend = {
    /**
     * Design system color intent
     */
    colorIntent: string;
    /**
     * Status identifier
     */
    id: string;
    /**
     * Human-readable label
     */
    label: string;
};

export type TaskSummary = {
    /**
     * Count of tasks with priority 'high'
     */
    highPriorityTasks: number;
    /**
     * Total number of tasks in the backlog
     */
    totalTasks: number;
    /**
     * Count of tasks with empty assignedTo
     */
    unassignedTasks: number;
    /**
     * Count of tasks with non-empty assignedTo where len(assignedTo) < peopleNeeded
     */
    understaffedTasks: number;
};

export type UpdatePersonInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Initials
     */
    initials: string;
    /**
     * Full name
     */
    name: string;
};

export type UpdatePlanningWindowInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * End date (ISO 8601, YYYY-MM-DD)
     */
    endDate: string;
    /**
     * Start date (ISO 8601, YYYY-MM-DD)
     */
    startDate: string;
};

export type UpdateRoomRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Updated human-readable room or area name
     */
    name: string;
    /**
     * One of: room, area
     */
    type: 'room' | 'area';
};

export type UpsertAvailabilityInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * One of: available, busy, partial, off
     */
    status: string;
};

export type UpsertAvailabilityOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
};

export type CreatePersonInputBodyWritable = {
    /**
     * Client-supplied stable person key (slug)
     */
    id: string;
    /**
     * Initials
     */
    initials: string;
    /**
     * Full name
     */
    name: string;
};

export type CreateRoomRequestBodyWritable = {
    /**
     * Human-readable room or area name
     */
    name: string;
    /**
     * One of: room, area
     */
    type: 'room' | 'area';
};

export type CreateTaskRequestBodyWritable = {
    /**
     * Person-ID strings for assigned helpers, may be empty
     */
    assignedTo: Array<string> | null;
    /**
     * Number of people required for the task, minimum 1
     */
    peopleNeeded: number;
    /**
     * One of: high, medium, low
     */
    priority: 'high' | 'medium' | 'low';
    /**
     * Room or area the task belongs to
     */
    room: string;
    /**
     * One of: backlog, ready, assigned
     */
    status: 'backlog' | 'ready' | 'assigned';
    /**
     * Human-readable task description
     */
    title: string;
};

export type DailyScheduleBodyWritable = {
    /**
     * One entry per date in the requested window
     */
    days: Array<ScheduleDay> | null;
    /**
     * Date range metadata
     */
    range: ScheduleRange;
};

export type DashboardBodyWritable = {
    /**
     * People with daily availability
     */
    people: Array<PersonWritable> | null;
    /**
     * Date range metadata
     */
    range: Range;
    /**
     * Canonical status legend
     */
    statuses: Array<StatusLegend> | null;
    /**
     * Summary counts
     */
    summary: Summary;
};

export type DeleteAvailabilityOutputBodyWritable = {
    message: string;
};

export type DeletePersonOutputBodyWritable = {
    message: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type HelloOutputBodyWritable = {
    message: string;
};

export type ListRoomsOutputBodyWritable = {
    /**
     * All room/area records
     */
    rooms: Array<RoomWritable> | null;
};

export type PersonWritable = {
    /**
     * One entry per date in the range
     */
    availability: Array<AvailabilityEntry> | null;
    /**
     * Stable person key
     */
    id: string;
    /**
     * Initials
     */
    initials: string;
    /**
     * Full name
     */
    name: string;
};

export type PlanningWindowBodyWritable = {
    /**
     * Inclusive day count between startDate and endDate
     */
    days: number;
    /**
     * End date of the planning window (ISO 8601)
     */
    endDate: string;
    /**
     * Start date of the planning window (ISO 8601)
     */
    startDate: string;
};

export type RoomWritable = {
    /**
     * ISO 8601 timestamp of creation
     */
    createdAt: string;
    /**
     * Stable room identifier, prefixed 'room-'
     */
    id: string;
    /**
     * Human-readable room or area name
     */
    name: string;
    /**
     * One of: room, area
     */
    type: 'room' | 'area';
    /**
     * ISO 8601 timestamp of last update
     */
    updatedAt: string;
};

export type TaskBacklogBodyWritable = {
    /**
     * Canonical priority legend
     */
    priorities: Array<PriorityLegend> | null;
    /**
     * Canonical task-status legend
     */
    statuses: Array<TaskStatusLegend> | null;
    /**
     * Derived summary counts
     */
    summary: TaskSummary;
    /**
     * Backlog task rows
     */
    tasks: Array<TaskRowWritable> | null;
};

export type TaskRowWritable = {
    /**
     * Person-ID strings for assigned helpers, may be empty
     */
    assignedTo: Array<string> | null;
    /**
     * Stable task identifier, prefixed 'task-'
     */
    id: string;
    /**
     * Number of people required for the task, minimum 1
     */
    peopleNeeded: number;
    /**
     * One of: high, medium, low
     */
    priority: string;
    /**
     * Room or area the task belongs to
     */
    room: string;
    /**
     * One of: backlog, ready, assigned
     */
    status: string;
    /**
     * Human-readable task description
     */
    title: string;
};

export type UpdatePersonInputBodyWritable = {
    /**
     * Initials
     */
    initials: string;
    /**
     * Full name
     */
    name: string;
};

export type UpdatePlanningWindowInputBodyWritable = {
    /**
     * End date (ISO 8601, YYYY-MM-DD)
     */
    endDate: string;
    /**
     * Start date (ISO 8601, YYYY-MM-DD)
     */
    startDate: string;
};

export type UpdateRoomRequestBodyWritable = {
    /**
     * Updated human-readable room or area name
     */
    name: string;
    /**
     * One of: room, area
     */
    type: 'room' | 'area';
};

export type UpsertAvailabilityInputBodyWritable = {
    /**
     * One of: available, busy, partial, off
     */
    status: string;
};

export type UpsertAvailabilityOutputBodyWritable = {
    message: string;
};

export type GetDashboardDailyScheduleData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start date in ISO 8601 format (YYYY-MM-DD). Defaults to the planning-window start date 2026-07-05.
         */
        start?: string;
        /**
         * Number of days inclusive of start date.
         */
        days?: number;
    };
    url: '/api/dashboard/daily-schedule';
};

export type GetDashboardDailyScheduleErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetDashboardDailyScheduleError = GetDashboardDailyScheduleErrors[keyof GetDashboardDailyScheduleErrors];

export type GetDashboardDailyScheduleResponses = {
    /**
     * OK
     */
    200: DailyScheduleBody;
};

export type GetDashboardDailyScheduleResponse = GetDashboardDailyScheduleResponses[keyof GetDashboardDailyScheduleResponses];

export type GetDashboardPeopleAvailabilityData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start date in ISO 8601 format (YYYY-MM-DD). Defaults to the server-local current date.
         */
        start?: string;
        /**
         * Number of days inclusive of start date.
         */
        days?: number;
    };
    url: '/api/dashboard/people-availability';
};

export type GetDashboardPeopleAvailabilityErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetDashboardPeopleAvailabilityError = GetDashboardPeopleAvailabilityErrors[keyof GetDashboardPeopleAvailabilityErrors];

export type GetDashboardPeopleAvailabilityResponses = {
    /**
     * OK
     */
    200: DashboardBody;
};

export type GetDashboardPeopleAvailabilityResponse = GetDashboardPeopleAvailabilityResponses[keyof GetDashboardPeopleAvailabilityResponses];

export type GetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/hello';
};

export type GetHelloErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetHelloError = GetHelloErrors[keyof GetHelloErrors];

export type GetHelloResponses = {
    /**
     * OK
     */
    200: HelloOutputBody;
};

export type GetHelloResponse = GetHelloResponses[keyof GetHelloResponses];

export type CreatePersonData = {
    body: CreatePersonInputBodyWritable;
    path?: never;
    query?: never;
    url: '/api/people';
};

export type CreatePersonErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreatePersonError = CreatePersonErrors[keyof CreatePersonErrors];

export type CreatePersonResponses = {
    /**
     * OK
     */
    200: Person;
};

export type CreatePersonResponse = CreatePersonResponses[keyof CreatePersonResponses];

export type DeletePersonData = {
    body?: never;
    path: {
        /**
         * Stable person key
         */
        id: string;
    };
    query?: never;
    url: '/api/people/{id}';
};

export type DeletePersonErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeletePersonError = DeletePersonErrors[keyof DeletePersonErrors];

export type DeletePersonResponses = {
    /**
     * OK
     */
    200: DeletePersonOutputBody;
};

export type DeletePersonResponse = DeletePersonResponses[keyof DeletePersonResponses];

export type UpdatePersonData = {
    body: UpdatePersonInputBodyWritable;
    path: {
        /**
         * Stable person key
         */
        id: string;
    };
    query?: never;
    url: '/api/people/{id}';
};

export type UpdatePersonErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdatePersonError = UpdatePersonErrors[keyof UpdatePersonErrors];

export type UpdatePersonResponses = {
    /**
     * OK
     */
    200: Person;
};

export type UpdatePersonResponse = UpdatePersonResponses[keyof UpdatePersonResponses];

export type DeletePersonAvailabilityData = {
    body?: never;
    path: {
        /**
         * Stable person key
         */
        id: string;
        /**
         * Date in ISO 8601 format (YYYY-MM-DD)
         */
        date: string;
    };
    query?: never;
    url: '/api/people/{id}/availability/{date}';
};

export type DeletePersonAvailabilityErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeletePersonAvailabilityError = DeletePersonAvailabilityErrors[keyof DeletePersonAvailabilityErrors];

export type DeletePersonAvailabilityResponses = {
    /**
     * OK
     */
    200: DeleteAvailabilityOutputBody;
};

export type DeletePersonAvailabilityResponse = DeletePersonAvailabilityResponses[keyof DeletePersonAvailabilityResponses];

export type UpsertPersonAvailabilityData = {
    body: UpsertAvailabilityInputBodyWritable;
    path: {
        /**
         * Stable person key
         */
        id: string;
        /**
         * Date in ISO 8601 format (YYYY-MM-DD)
         */
        date: string;
    };
    query?: never;
    url: '/api/people/{id}/availability/{date}';
};

export type UpsertPersonAvailabilityErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpsertPersonAvailabilityError = UpsertPersonAvailabilityErrors[keyof UpsertPersonAvailabilityErrors];

export type UpsertPersonAvailabilityResponses = {
    /**
     * OK
     */
    200: UpsertAvailabilityOutputBody;
};

export type UpsertPersonAvailabilityResponse = UpsertPersonAvailabilityResponses[keyof UpsertPersonAvailabilityResponses];

export type GetPlanningWindowData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/planning-window';
};

export type GetPlanningWindowErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetPlanningWindowError = GetPlanningWindowErrors[keyof GetPlanningWindowErrors];

export type GetPlanningWindowResponses = {
    /**
     * OK
     */
    200: PlanningWindowBody;
};

export type GetPlanningWindowResponse = GetPlanningWindowResponses[keyof GetPlanningWindowResponses];

export type PutPlanningWindowData = {
    body: UpdatePlanningWindowInputBodyWritable;
    path?: never;
    query?: never;
    url: '/api/planning-window';
};

export type PutPlanningWindowErrors = {
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type PutPlanningWindowError = PutPlanningWindowErrors[keyof PutPlanningWindowErrors];

export type PutPlanningWindowResponses = {
    /**
     * OK
     */
    200: PlanningWindowBody;
};

export type PutPlanningWindowResponse = PutPlanningWindowResponses[keyof PutPlanningWindowResponses];

export type ListRoomsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rooms';
};

export type ListRoomsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListRoomsError = ListRoomsErrors[keyof ListRoomsErrors];

export type ListRoomsResponses = {
    /**
     * OK
     */
    200: ListRoomsOutputBody;
};

export type ListRoomsResponse = ListRoomsResponses[keyof ListRoomsResponses];

export type CreateRoomData = {
    body: CreateRoomRequestBodyWritable;
    path?: never;
    query?: never;
    url: '/api/rooms';
};

export type CreateRoomErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateRoomError = CreateRoomErrors[keyof CreateRoomErrors];

export type CreateRoomResponses = {
    /**
     * Created
     */
    201: Room;
};

export type CreateRoomResponse = CreateRoomResponses[keyof CreateRoomResponses];

export type DeleteRoomData = {
    body?: never;
    path: {
        /**
         * Room identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/rooms/{id}';
};

export type DeleteRoomErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteRoomError = DeleteRoomErrors[keyof DeleteRoomErrors];

export type DeleteRoomResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRoomResponse = DeleteRoomResponses[keyof DeleteRoomResponses];

export type UpdateRoomData = {
    body: UpdateRoomRequestBodyWritable;
    path: {
        /**
         * Room identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/rooms/{id}';
};

export type UpdateRoomErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateRoomError = UpdateRoomErrors[keyof UpdateRoomErrors];

export type UpdateRoomResponses = {
    /**
     * OK
     */
    200: Room;
};

export type UpdateRoomResponse = UpdateRoomResponses[keyof UpdateRoomResponses];

export type CreateTaskData = {
    body: CreateTaskRequestBodyWritable;
    path?: never;
    query?: never;
    url: '/api/tasks';
};

export type CreateTaskErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateTaskError = CreateTaskErrors[keyof CreateTaskErrors];

export type CreateTaskResponses = {
    /**
     * OK
     */
    200: TaskRow;
};

export type CreateTaskResponse = CreateTaskResponses[keyof CreateTaskResponses];

export type GetTasksBacklogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tasks/backlog';
};

export type GetTasksBacklogErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetTasksBacklogError = GetTasksBacklogErrors[keyof GetTasksBacklogErrors];

export type GetTasksBacklogResponses = {
    /**
     * OK
     */
    200: TaskBacklogBody;
};

export type GetTasksBacklogResponse = GetTasksBacklogResponses[keyof GetTasksBacklogResponses];

export type DeleteTaskData = {
    body?: never;
    path: {
        /**
         * Task identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type DeleteTaskErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteTaskError = DeleteTaskErrors[keyof DeleteTaskErrors];

export type DeleteTaskResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteTaskResponse = DeleteTaskResponses[keyof DeleteTaskResponses];

export type UpdateTaskData = {
    body: CreateTaskRequestBodyWritable;
    path: {
        /**
         * Task identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type UpdateTaskErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateTaskError = UpdateTaskErrors[keyof UpdateTaskErrors];

export type UpdateTaskResponses = {
    /**
     * OK
     */
    200: TaskRow;
};

export type UpdateTaskResponse = UpdateTaskResponses[keyof UpdateTaskResponses];
