// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AssignedPerson = {
    /**
     * Stable person key
     */
    id: string;
    /**
     * Initials
     */
    initials: string;
    /**
     * Full name
     */
    name: string;
};

export type AvailabilityEntry = {
    /**
     * Date in ISO 8601 format (YYYY-MM-DD)
     */
    date: string;
    /**
     * One of: available, busy, partial, off
     */
    status: string;
};

export type DailyScheduleBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * One entry per date in the requested window
     */
    days: Array<ScheduleDay> | null;
    /**
     * Date range metadata
     */
    range: ScheduleRange;
};

export type DashboardBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * People with daily availability
     */
    people: Array<Person> | null;
    /**
     * Date range metadata
     */
    range: Range;
    /**
     * Canonical status legend
     */
    statuses: Array<StatusLegend> | null;
    /**
     * Summary counts
     */
    summary: Summary;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type HelloOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
};

export type Person = {
    /**
     * One entry per date in the range
     */
    availability: Array<AvailabilityEntry> | null;
    /**
     * Stable person key
     */
    id: string;
    /**
     * Initials
     */
    initials: string;
    /**
     * Full name
     */
    name: string;
};

export type PlanningWindowBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Inclusive day count between startDate and endDate
     */
    days: number;
    /**
     * End date of the planning window (ISO 8601)
     */
    endDate: string;
    /**
     * Start date of the planning window (ISO 8601)
     */
    startDate: string;
};

export type PriorityLegend = {
    /**
     * Design system color intent
     */
    colorIntent: string;
    /**
     * Priority identifier
     */
    id: string;
    /**
     * Human-readable label
     */
    label: string;
};

export type Range = {
    /**
     * Number of dates in the window (inclusive of startDate)
     */
    days: number;
    /**
     * End date of the window (ISO 8601)
     */
    endDate: string;
    /**
     * Reference date for summary counts (equals startDate)
     */
    selectedDate: string;
    /**
     * Start date of the window (ISO 8601)
     */
    startDate: string;
};

export type ScheduleDay = {
    /**
     * Number of people available on this date
     */
    availablePeopleCount: number;
    /**
     * Date in ISO 8601 format (YYYY-MM-DD)
     */
    date: string;
    /**
     * Human-readable day header
     */
    label: string;
    /**
     * Ordered schedule task cards
     */
    tasks: Array<TaskCard> | null;
};

export type ScheduleRange = {
    /**
     * Number of dates in the window (inclusive of startDate)
     */
    days: number;
    /**
     * End date of the window (ISO 8601)
     */
    endDate: string;
    /**
     * Start date of the window (ISO 8601)
     */
    startDate: string;
};

export type StatusLegend = {
    /**
     * Design system color intent
     */
    colorIntent: string;
    /**
     * Status identifier
     */
    id: string;
    /**
     * Human-readable label
     */
    label: string;
};

export type Summary = {
    /**
     * Number of people with status 'available' on selectedDate
     */
    availableToday: number;
    /**
     * Total number of people in the response
     */
    totalPeople: number;
};

export type TaskBacklogBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Canonical priority legend
     */
    priorities: Array<PriorityLegend> | null;
    /**
     * Canonical task-status legend
     */
    statuses: Array<TaskStatusLegend> | null;
    /**
     * Derived summary counts
     */
    summary: TaskSummary;
    /**
     * Backlog task rows
     */
    tasks: Array<TaskRow> | null;
};

export type TaskCard = {
    /**
     * Number of people currently assigned (derived from assignedPeople)
     */
    assignedCount: number;
    /**
     * People assigned to this task
     */
    assignedPeople: Array<AssignedPerson> | null;
    /**
     * Stable task identifier
     */
    id: string;
    /**
     * Number of people needed for the task (>=1)
     */
    peopleNeeded: number;
    /**
     * One of: high, medium, low
     */
    priority: string;
    /**
     * Room or area name
     */
    roomArea: string;
    /**
     * One of: fullyStaffed, underStaffed
     */
    staffingStatus: string;
    /**
     * Task title
     */
    title: string;
};

export type TaskRow = {
    /**
     * Person-ID strings for assigned helpers, may be empty
     */
    assignedTo: Array<string> | null;
    /**
     * Stable task identifier, prefixed 'task-'
     */
    id: string;
    /**
     * Number of people required for the task, minimum 1
     */
    peopleNeeded: number;
    /**
     * One of: high, medium, low
     */
    priority: string;
    /**
     * Room or area the task belongs to
     */
    room: string;
    /**
     * One of: backlog, ready, assigned
     */
    status: string;
    /**
     * Human-readable task description
     */
    title: string;
};

export type TaskStatusLegend = {
    /**
     * Design system color intent
     */
    colorIntent: string;
    /**
     * Status identifier
     */
    id: string;
    /**
     * Human-readable label
     */
    label: string;
};

export type TaskSummary = {
    /**
     * Count of tasks with priority 'high'
     */
    highPriorityTasks: number;
    /**
     * Total number of tasks in the backlog
     */
    totalTasks: number;
    /**
     * Count of tasks with empty assignedTo
     */
    unassignedTasks: number;
    /**
     * Count of tasks with non-empty assignedTo where len(assignedTo) < peopleNeeded
     */
    understaffedTasks: number;
};

export type UpdatePlanningWindowInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * End date (ISO 8601, YYYY-MM-DD)
     */
    endDate: string;
    /**
     * Start date (ISO 8601, YYYY-MM-DD)
     */
    startDate: string;
};

export type DailyScheduleBodyWritable = {
    /**
     * One entry per date in the requested window
     */
    days: Array<ScheduleDay> | null;
    /**
     * Date range metadata
     */
    range: ScheduleRange;
};

export type DashboardBodyWritable = {
    /**
     * People with daily availability
     */
    people: Array<Person> | null;
    /**
     * Date range metadata
     */
    range: Range;
    /**
     * Canonical status legend
     */
    statuses: Array<StatusLegend> | null;
    /**
     * Summary counts
     */
    summary: Summary;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type HelloOutputBodyWritable = {
    message: string;
};

export type PlanningWindowBodyWritable = {
    /**
     * Inclusive day count between startDate and endDate
     */
    days: number;
    /**
     * End date of the planning window (ISO 8601)
     */
    endDate: string;
    /**
     * Start date of the planning window (ISO 8601)
     */
    startDate: string;
};

export type TaskBacklogBodyWritable = {
    /**
     * Canonical priority legend
     */
    priorities: Array<PriorityLegend> | null;
    /**
     * Canonical task-status legend
     */
    statuses: Array<TaskStatusLegend> | null;
    /**
     * Derived summary counts
     */
    summary: TaskSummary;
    /**
     * Backlog task rows
     */
    tasks: Array<TaskRow> | null;
};

export type UpdatePlanningWindowInputBodyWritable = {
    /**
     * End date (ISO 8601, YYYY-MM-DD)
     */
    endDate: string;
    /**
     * Start date (ISO 8601, YYYY-MM-DD)
     */
    startDate: string;
};

export type GetDashboardDailyScheduleData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start date in ISO 8601 format (YYYY-MM-DD). Defaults to the planning-window start date 2026-07-05.
         */
        start?: string;
        /**
         * Number of days inclusive of start date.
         */
        days?: number;
    };
    url: '/api/dashboard/daily-schedule';
};

export type GetDashboardDailyScheduleErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetDashboardDailyScheduleError = GetDashboardDailyScheduleErrors[keyof GetDashboardDailyScheduleErrors];

export type GetDashboardDailyScheduleResponses = {
    /**
     * OK
     */
    200: DailyScheduleBody;
};

export type GetDashboardDailyScheduleResponse = GetDashboardDailyScheduleResponses[keyof GetDashboardDailyScheduleResponses];

export type GetDashboardPeopleAvailabilityData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start date in ISO 8601 format (YYYY-MM-DD). Defaults to the server-local current date.
         */
        start?: string;
        /**
         * Number of days inclusive of start date.
         */
        days?: number;
    };
    url: '/api/dashboard/people-availability';
};

export type GetDashboardPeopleAvailabilityErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetDashboardPeopleAvailabilityError = GetDashboardPeopleAvailabilityErrors[keyof GetDashboardPeopleAvailabilityErrors];

export type GetDashboardPeopleAvailabilityResponses = {
    /**
     * OK
     */
    200: DashboardBody;
};

export type GetDashboardPeopleAvailabilityResponse = GetDashboardPeopleAvailabilityResponses[keyof GetDashboardPeopleAvailabilityResponses];

export type GetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/hello';
};

export type GetHelloErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetHelloError = GetHelloErrors[keyof GetHelloErrors];

export type GetHelloResponses = {
    /**
     * OK
     */
    200: HelloOutputBody;
};

export type GetHelloResponse = GetHelloResponses[keyof GetHelloResponses];

export type GetPlanningWindowData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/planning-window';
};

export type GetPlanningWindowErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetPlanningWindowError = GetPlanningWindowErrors[keyof GetPlanningWindowErrors];

export type GetPlanningWindowResponses = {
    /**
     * OK
     */
    200: PlanningWindowBody;
};

export type GetPlanningWindowResponse = GetPlanningWindowResponses[keyof GetPlanningWindowResponses];

export type PutPlanningWindowData = {
    body: UpdatePlanningWindowInputBodyWritable;
    path?: never;
    query?: never;
    url: '/api/planning-window';
};

export type PutPlanningWindowErrors = {
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type PutPlanningWindowError = PutPlanningWindowErrors[keyof PutPlanningWindowErrors];

export type PutPlanningWindowResponses = {
    /**
     * OK
     */
    200: PlanningWindowBody;
};

export type PutPlanningWindowResponse = PutPlanningWindowResponses[keyof PutPlanningWindowResponses];

export type GetTasksBacklogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tasks/backlog';
};

export type GetTasksBacklogErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetTasksBacklogError = GetTasksBacklogErrors[keyof GetTasksBacklogErrors];

export type GetTasksBacklogResponses = {
    /**
     * OK
     */
    200: TaskBacklogBody;
};

export type GetTasksBacklogResponse = GetTasksBacklogResponses[keyof GetTasksBacklogResponses];
