// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Area = {
    /**
     * Stable room/area identifier, prefixed 'room-'
     */
    id: string;
    /**
     * Human-readable room or area name
     */
    name: string;
};

export type AssignedPerson = {
    /**
     * Stable person key
     */
    id: string;
    /**
     * Initials
     */
    initials: string;
    /**
     * Full name
     */
    name: string;
};

export type AvailabilityEntry = {
    /**
     * Date in ISO 8601 format (YYYY-MM-DD)
     */
    date: string;
    /**
     * One of: available, busy, partial, off
     */
    status: string;
};

export type CreatePersonInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Initials
     */
    initials: string;
    /**
     * Full name
     */
    name: string;
};

export type CreateRoomRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Human-readable room or area name
     */
    name: string;
    /**
     * One of: room, area
     */
    type: 'room' | 'area';
};

export type CreateScheduleCardRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * ID of the room or area (required unless taskId is provided)
     */
    areaId?: string;
    /**
     * Person-ID strings for assigned helpers, may be empty
     */
    assignedTo?: Array<string> | null;
    /**
     * Number of people needed for the task >=1 (required unless taskId is provided)
     */
    peopleNeeded?: number;
    /**
     * One of: high, medium, low (required unless taskId is provided)
     */
    priority?: 'high' | 'medium' | 'low';
    /**
     * ISO 8601 date (YYYY-MM-DD) the card is scheduled for
     */
    scheduledDate: string;
    /**
     * Referenced backlog task ID. When provided, title/priority/areaId/peopleNeeded inherit from the referenced task unless explicitly supplied.
     */
    taskId?: string;
    /**
     * Task title (required unless taskId is provided)
     */
    title?: string;
};

export type CreateTaskRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * ID of the room or area the task belongs to
     */
    areaId: string;
    /**
     * Person-ID strings for assigned helpers, may be empty
     */
    assignedTo: Array<string> | null;
    /**
     * Number of people required for the task, minimum 1
     */
    peopleNeeded: number;
    /**
     * One of: high, medium, low
     */
    priority: 'high' | 'medium' | 'low';
    /**
     * One of: backlog, ready, assigned
     */
    status: 'backlog' | 'ready' | 'assigned';
    /**
     * Human-readable task description
     */
    title: string;
};

export type CreateToolRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Human-readable tool name
     */
    name: string;
};

export type DailyScheduleBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * One entry per date in the requested window
     */
    days: Array<ScheduleDay> | null;
    /**
     * Date range metadata
     */
    range: ScheduleRange;
};

export type DashboardBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Pagination metadata
     */
    pagination: Pagination;
    /**
     * People with daily availability
     */
    people: Array<Person> | null;
    /**
     * Date range metadata
     */
    range: Range;
    /**
     * Canonical status legend
     */
    statuses: Array<StatusLegend> | null;
    /**
     * Summary counts
     */
    summary: Summary;
};

export type DeleteAvailabilityOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
};

export type DeletePersonOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type HelloOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
};

export type ListRoomsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * All room/area records
     */
    rooms: Array<Room> | null;
};

export type Pagination = {
    /**
     * 1-indexed current page number
     */
    page: number;
    /**
     * Number of people per page (equals limit when paginating, total when no limit)
     */
    perPage: number;
    /**
     * Total number of people regardless of pagination
     */
    totalPeople: number;
};

export type Person = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * One entry per date in the range
     */
    availability: Array<AvailabilityEntry> | null;
    /**
     * Stable person key
     */
    id: string;
    /**
     * Initials
     */
    initials: string;
    /**
     * Full name
     */
    name: string;
};

export type PlanningWindowBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Inclusive day count between startDate and endDate
     */
    days: number;
    /**
     * End date of the planning window (ISO 8601)
     */
    endDate: string;
    /**
     * Start date of the planning window (ISO 8601)
     */
    startDate: string;
};

export type PriorityLegend = {
    /**
     * Design system color intent
     */
    colorIntent: string;
    /**
     * Priority identifier
     */
    id: string;
    /**
     * Human-readable label
     */
    label: string;
};

export type Range = {
    /**
     * Number of dates in the window (inclusive of startDate)
     */
    days: number;
    /**
     * End date of the window (ISO 8601)
     */
    endDate: string;
    /**
     * Reference date for summary counts (equals startDate)
     */
    selectedDate: string;
    /**
     * Start date of the window (ISO 8601)
     */
    startDate: string;
};

export type Room = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * ISO 8601 timestamp of creation
     */
    createdAt: string;
    /**
     * Stable room identifier, prefixed 'room-'
     */
    id: string;
    /**
     * Human-readable room or area name
     */
    name: string;
    /**
     * One of: room, area
     */
    type: 'room' | 'area';
    /**
     * ISO 8601 timestamp of last update
     */
    updatedAt: string;
};

export type ScheduleDay = {
    /**
     * Number of people available on this date
     */
    availablePeopleCount: number;
    /**
     * Date in ISO 8601 format (YYYY-MM-DD)
     */
    date: string;
    /**
     * Human-readable day header
     */
    label: string;
    /**
     * Ordered schedule task cards
     */
    tasks: Array<TaskCard> | null;
};

export type ScheduleRange = {
    /**
     * Number of dates in the window (inclusive of startDate)
     */
    days: number;
    /**
     * End date of the window (ISO 8601)
     */
    endDate: string;
    /**
     * Start date of the window (ISO 8601)
     */
    startDate: string;
};

export type SetScheduleCardCompletedRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Whether the card is completed (true to mark done, false to revert)
     */
    completed: boolean;
};

export type SetToolBringerInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * ID of the person bringing the tool
     */
    personId: string;
};

export type StatusLegend = {
    /**
     * Design system color intent
     */
    colorIntent: string;
    /**
     * Status identifier
     */
    id: string;
    /**
     * Human-readable label
     */
    label: string;
};

export type Summary = {
    /**
     * Number of people with status 'available' on selectedDate
     */
    availableToday: number;
    /**
     * Total number of people regardless of pagination
     */
    totalPeople: number;
};

export type TaskBacklogBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Canonical priority legend
     */
    priorities: Array<PriorityLegend> | null;
    /**
     * Canonical task-status legend
     */
    statuses: Array<TaskStatusLegend> | null;
    /**
     * Derived summary counts
     */
    summary: TaskSummary;
    /**
     * Backlog task rows
     */
    tasks: Array<TaskRow> | null;
};

export type TaskCard = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Room or area the card belongs to
     */
    area: Area;
    /**
     * Number of people currently assigned (derived from assignedPeople)
     */
    assignedCount: number;
    /**
     * People assigned to this task
     */
    assignedPeople: Array<AssignedPerson> | null;
    /**
     * Whether the card is marked as done
     */
    completed: boolean;
    /**
     * Stable task identifier
     */
    id: string;
    /**
     * Number of people needed for the task (>=1)
     */
    peopleNeeded: number;
    /**
     * One of: high, medium, low
     */
    priority: string;
    /**
     * One of: fullyStaffed, underStaffed
     */
    staffingStatus: string;
    /**
     * Referenced backlog task ID, null if no reference
     */
    taskId: string | null;
    /**
     * Task title
     */
    title: string;
};

export type TaskRow = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Room or area the task belongs to
     */
    area: Area;
    /**
     * Person-ID strings for assigned helpers, may be empty
     */
    assignedTo: Array<string> | null;
    /**
     * Stable task identifier, prefixed 'task-'
     */
    id: string;
    /**
     * Number of people required for the task, minimum 1
     */
    peopleNeeded: number;
    /**
     * One of: high, medium, low
     */
    priority: string;
    /**
     * One of: backlog, ready, assigned
     */
    status: string;
    /**
     * Human-readable task description
     */
    title: string;
};

export type TaskStatusLegend = {
    /**
     * Design system color intent
     */
    colorIntent: string;
    /**
     * Status identifier
     */
    id: string;
    /**
     * Human-readable label
     */
    label: string;
};

export type TaskSummary = {
    /**
     * Count of tasks with priority 'high'
     */
    highPriorityTasks: number;
    /**
     * Total number of tasks in the backlog
     */
    totalTasks: number;
    /**
     * Count of tasks with empty assignedTo
     */
    unassignedTasks: number;
    /**
     * Count of tasks with non-empty assignedTo where len(assignedTo) < peopleNeeded
     */
    understaffedTasks: number;
};

export type Tool = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Bringer's person ID, or null when the tool is open
     */
    broughtBy: string | null;
    /**
     * Stable tool identifier, prefixed 'tool-'
     */
    id: string;
    /**
     * Human-readable tool name
     */
    name: string;
};

export type ToolSummary = {
    /**
     * Count of tools with a bringer (crossed off)
     */
    claimed: number;
    /**
     * Count of tools without a bringer
     */
    open: number;
    /**
     * Total number of tools
     */
    total: number;
};

export type ToolsBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Derived coverage summary
     */
    summary: ToolSummary;
    /**
     * Tool rows ordered by sort order
     */
    tools: Array<Tool> | null;
};

export type UpdatePersonInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Initials
     */
    initials: string;
    /**
     * Full name
     */
    name: string;
};

export type UpdatePlanningWindowInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * End date (ISO 8601, YYYY-MM-DD)
     */
    endDate: string;
    /**
     * Start date (ISO 8601, YYYY-MM-DD)
     */
    startDate: string;
};

export type UpdateRoomRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Updated human-readable room or area name
     */
    name: string;
    /**
     * One of: room, area
     */
    type: 'room' | 'area';
};

export type UpdateToolRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Updated tool name
     */
    name: string;
    /**
     * Stable sort order
     */
    sortOrder: number;
};

export type UpsertAvailabilityInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * One of: available, busy, partial, off
     */
    status: string;
};

export type UpsertAvailabilityOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
};

export type CreatePersonInputBodyWritable = {
    /**
     * Initials
     */
    initials: string;
    /**
     * Full name
     */
    name: string;
};

export type CreateRoomRequestBodyWritable = {
    /**
     * Human-readable room or area name
     */
    name: string;
    /**
     * One of: room, area
     */
    type: 'room' | 'area';
};

export type CreateScheduleCardRequestBodyWritable = {
    /**
     * ID of the room or area (required unless taskId is provided)
     */
    areaId?: string;
    /**
     * Person-ID strings for assigned helpers, may be empty
     */
    assignedTo?: Array<string> | null;
    /**
     * Number of people needed for the task >=1 (required unless taskId is provided)
     */
    peopleNeeded?: number;
    /**
     * One of: high, medium, low (required unless taskId is provided)
     */
    priority?: 'high' | 'medium' | 'low';
    /**
     * ISO 8601 date (YYYY-MM-DD) the card is scheduled for
     */
    scheduledDate: string;
    /**
     * Referenced backlog task ID. When provided, title/priority/areaId/peopleNeeded inherit from the referenced task unless explicitly supplied.
     */
    taskId?: string;
    /**
     * Task title (required unless taskId is provided)
     */
    title?: string;
};

export type CreateTaskRequestBodyWritable = {
    /**
     * ID of the room or area the task belongs to
     */
    areaId: string;
    /**
     * Person-ID strings for assigned helpers, may be empty
     */
    assignedTo: Array<string> | null;
    /**
     * Number of people required for the task, minimum 1
     */
    peopleNeeded: number;
    /**
     * One of: high, medium, low
     */
    priority: 'high' | 'medium' | 'low';
    /**
     * One of: backlog, ready, assigned
     */
    status: 'backlog' | 'ready' | 'assigned';
    /**
     * Human-readable task description
     */
    title: string;
};

export type CreateToolRequestBodyWritable = {
    /**
     * Human-readable tool name
     */
    name: string;
};

export type DailyScheduleBodyWritable = {
    /**
     * One entry per date in the requested window
     */
    days: Array<ScheduleDayWritable> | null;
    /**
     * Date range metadata
     */
    range: ScheduleRange;
};

export type DashboardBodyWritable = {
    /**
     * Pagination metadata
     */
    pagination: Pagination;
    /**
     * People with daily availability
     */
    people: Array<PersonWritable> | null;
    /**
     * Date range metadata
     */
    range: Range;
    /**
     * Canonical status legend
     */
    statuses: Array<StatusLegend> | null;
    /**
     * Summary counts
     */
    summary: Summary;
};

export type DeleteAvailabilityOutputBodyWritable = {
    message: string;
};

export type DeletePersonOutputBodyWritable = {
    message: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type HelloOutputBodyWritable = {
    message: string;
};

export type ListRoomsOutputBodyWritable = {
    /**
     * All room/area records
     */
    rooms: Array<RoomWritable> | null;
};

export type PersonWritable = {
    /**
     * One entry per date in the range
     */
    availability: Array<AvailabilityEntry> | null;
    /**
     * Stable person key
     */
    id: string;
    /**
     * Initials
     */
    initials: string;
    /**
     * Full name
     */
    name: string;
};

export type PlanningWindowBodyWritable = {
    /**
     * Inclusive day count between startDate and endDate
     */
    days: number;
    /**
     * End date of the planning window (ISO 8601)
     */
    endDate: string;
    /**
     * Start date of the planning window (ISO 8601)
     */
    startDate: string;
};

export type RoomWritable = {
    /**
     * ISO 8601 timestamp of creation
     */
    createdAt: string;
    /**
     * Stable room identifier, prefixed 'room-'
     */
    id: string;
    /**
     * Human-readable room or area name
     */
    name: string;
    /**
     * One of: room, area
     */
    type: 'room' | 'area';
    /**
     * ISO 8601 timestamp of last update
     */
    updatedAt: string;
};

export type ScheduleDayWritable = {
    /**
     * Number of people available on this date
     */
    availablePeopleCount: number;
    /**
     * Date in ISO 8601 format (YYYY-MM-DD)
     */
    date: string;
    /**
     * Human-readable day header
     */
    label: string;
    /**
     * Ordered schedule task cards
     */
    tasks: Array<TaskCardWritable> | null;
};

export type SetScheduleCardCompletedRequestBodyWritable = {
    /**
     * Whether the card is completed (true to mark done, false to revert)
     */
    completed: boolean;
};

export type SetToolBringerInputBodyWritable = {
    /**
     * ID of the person bringing the tool
     */
    personId: string;
};

export type TaskBacklogBodyWritable = {
    /**
     * Canonical priority legend
     */
    priorities: Array<PriorityLegend> | null;
    /**
     * Canonical task-status legend
     */
    statuses: Array<TaskStatusLegend> | null;
    /**
     * Derived summary counts
     */
    summary: TaskSummary;
    /**
     * Backlog task rows
     */
    tasks: Array<TaskRowWritable> | null;
};

export type TaskCardWritable = {
    /**
     * Room or area the card belongs to
     */
    area: Area;
    /**
     * Number of people currently assigned (derived from assignedPeople)
     */
    assignedCount: number;
    /**
     * People assigned to this task
     */
    assignedPeople: Array<AssignedPerson> | null;
    /**
     * Whether the card is marked as done
     */
    completed: boolean;
    /**
     * Stable task identifier
     */
    id: string;
    /**
     * Number of people needed for the task (>=1)
     */
    peopleNeeded: number;
    /**
     * One of: high, medium, low
     */
    priority: string;
    /**
     * One of: fullyStaffed, underStaffed
     */
    staffingStatus: string;
    /**
     * Referenced backlog task ID, null if no reference
     */
    taskId: string | null;
    /**
     * Task title
     */
    title: string;
};

export type TaskRowWritable = {
    /**
     * Room or area the task belongs to
     */
    area: Area;
    /**
     * Person-ID strings for assigned helpers, may be empty
     */
    assignedTo: Array<string> | null;
    /**
     * Stable task identifier, prefixed 'task-'
     */
    id: string;
    /**
     * Number of people required for the task, minimum 1
     */
    peopleNeeded: number;
    /**
     * One of: high, medium, low
     */
    priority: string;
    /**
     * One of: backlog, ready, assigned
     */
    status: string;
    /**
     * Human-readable task description
     */
    title: string;
};

export type ToolWritable = {
    /**
     * Bringer's person ID, or null when the tool is open
     */
    broughtBy: string | null;
    /**
     * Stable tool identifier, prefixed 'tool-'
     */
    id: string;
    /**
     * Human-readable tool name
     */
    name: string;
};

export type ToolsBodyWritable = {
    /**
     * Derived coverage summary
     */
    summary: ToolSummary;
    /**
     * Tool rows ordered by sort order
     */
    tools: Array<ToolWritable> | null;
};

export type UpdatePersonInputBodyWritable = {
    /**
     * Initials
     */
    initials: string;
    /**
     * Full name
     */
    name: string;
};

export type UpdatePlanningWindowInputBodyWritable = {
    /**
     * End date (ISO 8601, YYYY-MM-DD)
     */
    endDate: string;
    /**
     * Start date (ISO 8601, YYYY-MM-DD)
     */
    startDate: string;
};

export type UpdateRoomRequestBodyWritable = {
    /**
     * Updated human-readable room or area name
     */
    name: string;
    /**
     * One of: room, area
     */
    type: 'room' | 'area';
};

export type UpdateToolRequestBodyWritable = {
    /**
     * Updated tool name
     */
    name: string;
    /**
     * Stable sort order
     */
    sortOrder: number;
};

export type UpsertAvailabilityInputBodyWritable = {
    /**
     * One of: available, busy, partial, off
     */
    status: string;
};

export type UpsertAvailabilityOutputBodyWritable = {
    message: string;
};

export type GetDashboardDailyScheduleData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start date in ISO 8601 format (YYYY-MM-DD). Defaults to the planning-window start date 2026-07-05.
         */
        start?: string;
        /**
         * Number of days inclusive of start date.
         */
        days?: number;
    };
    url: '/api/dashboard/daily-schedule';
};

export type GetDashboardDailyScheduleErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetDashboardDailyScheduleError = GetDashboardDailyScheduleErrors[keyof GetDashboardDailyScheduleErrors];

export type GetDashboardDailyScheduleResponses = {
    /**
     * OK
     */
    200: DailyScheduleBody;
};

export type GetDashboardDailyScheduleResponse = GetDashboardDailyScheduleResponses[keyof GetDashboardDailyScheduleResponses];

export type GetDashboardPeopleAvailabilityData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start date in ISO 8601 format (YYYY-MM-DD). Defaults to the planning-window start date.
         */
        start?: string;
        /**
         * Number of days inclusive of start date.
         */
        days?: number;
        /**
         * Number of people to skip. Default 0.
         */
        offset?: number;
        /**
         * Maximum number of people to return. 0 means no limit (return all).
         */
        limit?: number;
    };
    url: '/api/dashboard/people-availability';
};

export type GetDashboardPeopleAvailabilityErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetDashboardPeopleAvailabilityError = GetDashboardPeopleAvailabilityErrors[keyof GetDashboardPeopleAvailabilityErrors];

export type GetDashboardPeopleAvailabilityResponses = {
    /**
     * OK
     */
    200: DashboardBody;
};

export type GetDashboardPeopleAvailabilityResponse = GetDashboardPeopleAvailabilityResponses[keyof GetDashboardPeopleAvailabilityResponses];

export type GetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/hello';
};

export type GetHelloErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetHelloError = GetHelloErrors[keyof GetHelloErrors];

export type GetHelloResponses = {
    /**
     * OK
     */
    200: HelloOutputBody;
};

export type GetHelloResponse = GetHelloResponses[keyof GetHelloResponses];

export type CreatePersonData = {
    body: CreatePersonInputBodyWritable;
    path?: never;
    query?: never;
    url: '/api/people';
};

export type CreatePersonErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreatePersonError = CreatePersonErrors[keyof CreatePersonErrors];

export type CreatePersonResponses = {
    /**
     * Created
     */
    201: Person;
};

export type CreatePersonResponse = CreatePersonResponses[keyof CreatePersonResponses];

export type DeletePersonData = {
    body?: never;
    path: {
        /**
         * Stable person key
         */
        id: string;
    };
    query?: never;
    url: '/api/people/{id}';
};

export type DeletePersonErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeletePersonError = DeletePersonErrors[keyof DeletePersonErrors];

export type DeletePersonResponses = {
    /**
     * OK
     */
    200: DeletePersonOutputBody;
};

export type DeletePersonResponse = DeletePersonResponses[keyof DeletePersonResponses];

export type UpdatePersonData = {
    body: UpdatePersonInputBodyWritable;
    path: {
        /**
         * Stable person key
         */
        id: string;
    };
    query?: never;
    url: '/api/people/{id}';
};

export type UpdatePersonErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdatePersonError = UpdatePersonErrors[keyof UpdatePersonErrors];

export type UpdatePersonResponses = {
    /**
     * OK
     */
    200: Person;
};

export type UpdatePersonResponse = UpdatePersonResponses[keyof UpdatePersonResponses];

export type DeletePersonAvailabilityData = {
    body?: never;
    path: {
        /**
         * Stable person key
         */
        id: string;
        /**
         * Date in ISO 8601 format (YYYY-MM-DD)
         */
        date: string;
    };
    query?: never;
    url: '/api/people/{id}/availability/{date}';
};

export type DeletePersonAvailabilityErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeletePersonAvailabilityError = DeletePersonAvailabilityErrors[keyof DeletePersonAvailabilityErrors];

export type DeletePersonAvailabilityResponses = {
    /**
     * OK
     */
    200: DeleteAvailabilityOutputBody;
};

export type DeletePersonAvailabilityResponse = DeletePersonAvailabilityResponses[keyof DeletePersonAvailabilityResponses];

export type UpsertPersonAvailabilityData = {
    body: UpsertAvailabilityInputBodyWritable;
    path: {
        /**
         * Stable person key
         */
        id: string;
        /**
         * Date in ISO 8601 format (YYYY-MM-DD)
         */
        date: string;
    };
    query?: never;
    url: '/api/people/{id}/availability/{date}';
};

export type UpsertPersonAvailabilityErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpsertPersonAvailabilityError = UpsertPersonAvailabilityErrors[keyof UpsertPersonAvailabilityErrors];

export type UpsertPersonAvailabilityResponses = {
    /**
     * OK
     */
    200: UpsertAvailabilityOutputBody;
};

export type UpsertPersonAvailabilityResponse = UpsertPersonAvailabilityResponses[keyof UpsertPersonAvailabilityResponses];

export type GetPlanningWindowData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/planning-window';
};

export type GetPlanningWindowErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetPlanningWindowError = GetPlanningWindowErrors[keyof GetPlanningWindowErrors];

export type GetPlanningWindowResponses = {
    /**
     * OK
     */
    200: PlanningWindowBody;
};

export type GetPlanningWindowResponse = GetPlanningWindowResponses[keyof GetPlanningWindowResponses];

export type PutPlanningWindowData = {
    body: UpdatePlanningWindowInputBodyWritable;
    path?: never;
    query?: never;
    url: '/api/planning-window';
};

export type PutPlanningWindowErrors = {
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type PutPlanningWindowError = PutPlanningWindowErrors[keyof PutPlanningWindowErrors];

export type PutPlanningWindowResponses = {
    /**
     * OK
     */
    200: PlanningWindowBody;
};

export type PutPlanningWindowResponse = PutPlanningWindowResponses[keyof PutPlanningWindowResponses];

export type ListRoomsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rooms';
};

export type ListRoomsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListRoomsError = ListRoomsErrors[keyof ListRoomsErrors];

export type ListRoomsResponses = {
    /**
     * OK
     */
    200: ListRoomsOutputBody;
};

export type ListRoomsResponse = ListRoomsResponses[keyof ListRoomsResponses];

export type CreateRoomData = {
    body: CreateRoomRequestBodyWritable;
    path?: never;
    query?: never;
    url: '/api/rooms';
};

export type CreateRoomErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateRoomError = CreateRoomErrors[keyof CreateRoomErrors];

export type CreateRoomResponses = {
    /**
     * Created
     */
    201: Room;
};

export type CreateRoomResponse = CreateRoomResponses[keyof CreateRoomResponses];

export type DeleteRoomData = {
    body?: never;
    path: {
        /**
         * Room identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/rooms/{id}';
};

export type DeleteRoomErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteRoomError = DeleteRoomErrors[keyof DeleteRoomErrors];

export type DeleteRoomResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRoomResponse = DeleteRoomResponses[keyof DeleteRoomResponses];

export type UpdateRoomData = {
    body: UpdateRoomRequestBodyWritable;
    path: {
        /**
         * Room identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/rooms/{id}';
};

export type UpdateRoomErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateRoomError = UpdateRoomErrors[keyof UpdateRoomErrors];

export type UpdateRoomResponses = {
    /**
     * OK
     */
    200: Room;
};

export type UpdateRoomResponse = UpdateRoomResponses[keyof UpdateRoomResponses];

export type CreateScheduleCardData = {
    body: CreateScheduleCardRequestBodyWritable;
    path?: never;
    query?: never;
    url: '/api/schedule/cards';
};

export type CreateScheduleCardErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateScheduleCardError = CreateScheduleCardErrors[keyof CreateScheduleCardErrors];

export type CreateScheduleCardResponses = {
    /**
     * OK
     */
    200: TaskCard;
};

export type CreateScheduleCardResponse = CreateScheduleCardResponses[keyof CreateScheduleCardResponses];

export type DeleteScheduleCardData = {
    body?: never;
    path: {
        /**
         * Schedule card identifier (e.g., sched-1)
         */
        id: string;
    };
    query?: never;
    url: '/api/schedule/cards/{id}';
};

export type DeleteScheduleCardErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteScheduleCardError = DeleteScheduleCardErrors[keyof DeleteScheduleCardErrors];

export type DeleteScheduleCardResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteScheduleCardResponse = DeleteScheduleCardResponses[keyof DeleteScheduleCardResponses];

export type UpdateScheduleCardData = {
    body: CreateScheduleCardRequestBodyWritable;
    path: {
        /**
         * Schedule card identifier (e.g., sched-1)
         */
        id: string;
    };
    query?: never;
    url: '/api/schedule/cards/{id}';
};

export type UpdateScheduleCardErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateScheduleCardError = UpdateScheduleCardErrors[keyof UpdateScheduleCardErrors];

export type UpdateScheduleCardResponses = {
    /**
     * OK
     */
    200: TaskCard;
};

export type UpdateScheduleCardResponse = UpdateScheduleCardResponses[keyof UpdateScheduleCardResponses];

export type SetScheduleCardCompletedData = {
    body: SetScheduleCardCompletedRequestBodyWritable;
    path: {
        /**
         * Schedule card identifier (e.g., sched-1)
         */
        id: string;
    };
    query?: never;
    url: '/api/schedule/cards/{id}/complete';
};

export type SetScheduleCardCompletedErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SetScheduleCardCompletedError = SetScheduleCardCompletedErrors[keyof SetScheduleCardCompletedErrors];

export type SetScheduleCardCompletedResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SetScheduleCardCompletedResponse = SetScheduleCardCompletedResponses[keyof SetScheduleCardCompletedResponses];

export type CreateTaskData = {
    body: CreateTaskRequestBodyWritable;
    path?: never;
    query?: never;
    url: '/api/tasks';
};

export type CreateTaskErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateTaskError = CreateTaskErrors[keyof CreateTaskErrors];

export type CreateTaskResponses = {
    /**
     * OK
     */
    200: TaskRow;
};

export type CreateTaskResponse = CreateTaskResponses[keyof CreateTaskResponses];

export type GetTasksBacklogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tasks/backlog';
};

export type GetTasksBacklogErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetTasksBacklogError = GetTasksBacklogErrors[keyof GetTasksBacklogErrors];

export type GetTasksBacklogResponses = {
    /**
     * OK
     */
    200: TaskBacklogBody;
};

export type GetTasksBacklogResponse = GetTasksBacklogResponses[keyof GetTasksBacklogResponses];

export type DeleteTaskData = {
    body?: never;
    path: {
        /**
         * Task identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type DeleteTaskErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteTaskError = DeleteTaskErrors[keyof DeleteTaskErrors];

export type DeleteTaskResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteTaskResponse = DeleteTaskResponses[keyof DeleteTaskResponses];

export type UpdateTaskData = {
    body: CreateTaskRequestBodyWritable;
    path: {
        /**
         * Task identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type UpdateTaskErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateTaskError = UpdateTaskErrors[keyof UpdateTaskErrors];

export type UpdateTaskResponses = {
    /**
     * OK
     */
    200: TaskRow;
};

export type UpdateTaskResponse = UpdateTaskResponses[keyof UpdateTaskResponses];

export type GetToolsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tools';
};

export type GetToolsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetToolsError = GetToolsErrors[keyof GetToolsErrors];

export type GetToolsResponses = {
    /**
     * OK
     */
    200: ToolsBody;
};

export type GetToolsResponse = GetToolsResponses[keyof GetToolsResponses];

export type CreateToolData = {
    body: CreateToolRequestBodyWritable;
    path?: never;
    query?: never;
    url: '/api/tools';
};

export type CreateToolErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateToolError = CreateToolErrors[keyof CreateToolErrors];

export type CreateToolResponses = {
    /**
     * Created
     */
    201: Tool;
};

export type CreateToolResponse = CreateToolResponses[keyof CreateToolResponses];

export type DeleteToolData = {
    body?: never;
    path: {
        /**
         * Tool identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/tools/{id}';
};

export type DeleteToolErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteToolError = DeleteToolErrors[keyof DeleteToolErrors];

export type DeleteToolResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteToolResponse = DeleteToolResponses[keyof DeleteToolResponses];

export type UpdateToolData = {
    body: UpdateToolRequestBodyWritable;
    path: {
        /**
         * Tool identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/tools/{id}';
};

export type UpdateToolErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateToolError = UpdateToolErrors[keyof UpdateToolErrors];

export type UpdateToolResponses = {
    /**
     * OK
     */
    200: Tool;
};

export type UpdateToolResponse = UpdateToolResponses[keyof UpdateToolResponses];

export type ClearToolBringerData = {
    body?: never;
    path: {
        /**
         * Tool identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/tools/{id}/bringer';
};

export type ClearToolBringerErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ClearToolBringerError = ClearToolBringerErrors[keyof ClearToolBringerErrors];

export type ClearToolBringerResponses = {
    /**
     * No Content
     */
    204: void;
};

export type ClearToolBringerResponse = ClearToolBringerResponses[keyof ClearToolBringerResponses];

export type SetToolBringerData = {
    body: SetToolBringerInputBodyWritable;
    path: {
        /**
         * Tool identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/tools/{id}/bringer';
};

export type SetToolBringerErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SetToolBringerError = SetToolBringerErrors[keyof SetToolBringerErrors];

export type SetToolBringerResponses = {
    /**
     * OK
     */
    200: Tool;
};

export type SetToolBringerResponse = SetToolBringerResponses[keyof SetToolBringerResponses];
