// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_schedule.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScheduleAssignment = `-- name: CreateScheduleAssignment :exec
INSERT INTO schedule_task_assignments (task_card_id, person_id, sort_order)
VALUES ($1, $2, $3)
`

type CreateScheduleAssignmentParams struct {
	TaskCardID int32
	PersonID   string
	SortOrder  int32
}

func (q *Queries) CreateScheduleAssignment(ctx context.Context, arg CreateScheduleAssignmentParams) error {
	_, err := q.db.Exec(ctx, createScheduleAssignment, arg.TaskCardID, arg.PersonID, arg.SortOrder)
	return err
}

const createScheduleCard = `-- name: CreateScheduleCard :one
INSERT INTO schedule_task_cards (title, priority, room_area, people_needed, scheduled_date, sort_order, task_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, priority, room_area, people_needed, scheduled_date, sort_order, created_at, task_id
`

type CreateScheduleCardParams struct {
	Title         string
	Priority      string
	RoomArea      string
	PeopleNeeded  int32
	ScheduledDate pgtype.Date
	SortOrder     int32
	TaskID        pgtype.Text
}

type CreateScheduleCardRow struct {
	ID            int32
	Title         string
	Priority      string
	RoomArea      string
	PeopleNeeded  int32
	ScheduledDate pgtype.Date
	SortOrder     int32
	CreatedAt     pgtype.Timestamptz
	TaskID        pgtype.Text
}

func (q *Queries) CreateScheduleCard(ctx context.Context, arg CreateScheduleCardParams) (CreateScheduleCardRow, error) {
	row := q.db.QueryRow(ctx, createScheduleCard,
		arg.Title,
		arg.Priority,
		arg.RoomArea,
		arg.PeopleNeeded,
		arg.ScheduledDate,
		arg.SortOrder,
		arg.TaskID,
	)
	var i CreateScheduleCardRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Priority,
		&i.RoomArea,
		&i.PeopleNeeded,
		&i.ScheduledDate,
		&i.SortOrder,
		&i.CreatedAt,
		&i.TaskID,
	)
	return i, err
}

const deleteScheduleAssignments = `-- name: DeleteScheduleAssignments :exec
DELETE FROM schedule_task_assignments
WHERE task_card_id = $1
`

func (q *Queries) DeleteScheduleAssignments(ctx context.Context, taskCardID int32) error {
	_, err := q.db.Exec(ctx, deleteScheduleAssignments, taskCardID)
	return err
}

const deleteScheduleCard = `-- name: DeleteScheduleCard :exec
DELETE FROM schedule_task_cards
WHERE id = $1
`

func (q *Queries) DeleteScheduleCard(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteScheduleCard, id)
	return err
}

const getAvailableCountByDate = `-- name: GetAvailableCountByDate :many
SELECT a.date, COUNT(*)::int AS available_count
FROM availability a
WHERE a.status = 'available'
  AND a.date >= $1::date
  AND a.date < ($1::date + $2::int * interval '1 day')
GROUP BY a.date
ORDER BY a.date
`

type GetAvailableCountByDateParams struct {
	StartDate pgtype.Date
	Days      int32
}

type GetAvailableCountByDateRow struct {
	Date           pgtype.Date
	AvailableCount int32
}

func (q *Queries) GetAvailableCountByDate(ctx context.Context, arg GetAvailableCountByDateParams) ([]GetAvailableCountByDateRow, error) {
	rows, err := q.db.Query(ctx, getAvailableCountByDate, arg.StartDate, arg.Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAvailableCountByDateRow
	for rows.Next() {
		var i GetAvailableCountByDateRow
		if err := rows.Scan(&i.Date, &i.AvailableCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyScheduleAssignments = `-- name: GetDailyScheduleAssignments :many
SELECT task_card_id, person_id
FROM schedule_task_assignments
ORDER BY task_card_id, sort_order
`

type GetDailyScheduleAssignmentsRow struct {
	TaskCardID int32
	PersonID   string
}

func (q *Queries) GetDailyScheduleAssignments(ctx context.Context) ([]GetDailyScheduleAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, getDailyScheduleAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyScheduleAssignmentsRow
	for rows.Next() {
		var i GetDailyScheduleAssignmentsRow
		if err := rows.Scan(&i.TaskCardID, &i.PersonID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyScheduleTaskCards = `-- name: GetDailyScheduleTaskCards :many
SELECT id, title, priority, room_area, people_needed, scheduled_date, sort_order, created_at, task_id
FROM schedule_task_cards
WHERE scheduled_date >= $1::date
  AND scheduled_date < ($1::date + $2::int * interval '1 day')
ORDER BY scheduled_date, sort_order
`

type GetDailyScheduleTaskCardsParams struct {
	StartDate pgtype.Date
	Days      int32
}

type GetDailyScheduleTaskCardsRow struct {
	ID            int32
	Title         string
	Priority      string
	RoomArea      string
	PeopleNeeded  int32
	ScheduledDate pgtype.Date
	SortOrder     int32
	CreatedAt     pgtype.Timestamptz
	TaskID        pgtype.Text
}

func (q *Queries) GetDailyScheduleTaskCards(ctx context.Context, arg GetDailyScheduleTaskCardsParams) ([]GetDailyScheduleTaskCardsRow, error) {
	rows, err := q.db.Query(ctx, getDailyScheduleTaskCards, arg.StartDate, arg.Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyScheduleTaskCardsRow
	for rows.Next() {
		var i GetDailyScheduleTaskCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Priority,
			&i.RoomArea,
			&i.PeopleNeeded,
			&i.ScheduledDate,
			&i.SortOrder,
			&i.CreatedAt,
			&i.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxScheduleSortOrder = `-- name: GetMaxScheduleSortOrder :one
SELECT COALESCE(MAX(sort_order), 0)::int AS max_sort_order
FROM schedule_task_cards
`

func (q *Queries) GetMaxScheduleSortOrder(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxScheduleSortOrder)
	var max_sort_order int32
	err := row.Scan(&max_sort_order)
	return max_sort_order, err
}

const getScheduleCardByID = `-- name: GetScheduleCardByID :one
SELECT id, title, priority, room_area, people_needed, scheduled_date, sort_order, created_at, task_id
FROM schedule_task_cards
WHERE id = $1
`

type GetScheduleCardByIDRow struct {
	ID            int32
	Title         string
	Priority      string
	RoomArea      string
	PeopleNeeded  int32
	ScheduledDate pgtype.Date
	SortOrder     int32
	CreatedAt     pgtype.Timestamptz
	TaskID        pgtype.Text
}

func (q *Queries) GetScheduleCardByID(ctx context.Context, id int32) (GetScheduleCardByIDRow, error) {
	row := q.db.QueryRow(ctx, getScheduleCardByID, id)
	var i GetScheduleCardByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Priority,
		&i.RoomArea,
		&i.PeopleNeeded,
		&i.ScheduledDate,
		&i.SortOrder,
		&i.CreatedAt,
		&i.TaskID,
	)
	return i, err
}

const updateScheduleCard = `-- name: UpdateScheduleCard :one
UPDATE schedule_task_cards
SET title = $1,
    priority = $2,
    room_area = $3,
    people_needed = $4,
    scheduled_date = $5,
    sort_order = $6,
    task_id = $7
WHERE id = $8
RETURNING id, title, priority, room_area, people_needed, scheduled_date, sort_order, created_at, task_id
`

type UpdateScheduleCardParams struct {
	Title         string
	Priority      string
	RoomArea      string
	PeopleNeeded  int32
	ScheduledDate pgtype.Date
	SortOrder     int32
	TaskID        pgtype.Text
	ID            int32
}

type UpdateScheduleCardRow struct {
	ID            int32
	Title         string
	Priority      string
	RoomArea      string
	PeopleNeeded  int32
	ScheduledDate pgtype.Date
	SortOrder     int32
	CreatedAt     pgtype.Timestamptz
	TaskID        pgtype.Text
}

func (q *Queries) UpdateScheduleCard(ctx context.Context, arg UpdateScheduleCardParams) (UpdateScheduleCardRow, error) {
	row := q.db.QueryRow(ctx, updateScheduleCard,
		arg.Title,
		arg.Priority,
		arg.RoomArea,
		arg.PeopleNeeded,
		arg.ScheduledDate,
		arg.SortOrder,
		arg.TaskID,
		arg.ID,
	)
	var i UpdateScheduleCardRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Priority,
		&i.RoomArea,
		&i.PeopleNeeded,
		&i.ScheduledDate,
		&i.SortOrder,
		&i.CreatedAt,
		&i.TaskID,
	)
	return i, err
}

const taskExists = `-- name: TaskExists :one
SELECT EXISTS (
  SELECT 1 FROM backlog_tasks WHERE id = $1
)
`

func (q *Queries) TaskExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, taskExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const taskHasScheduleCards = `-- name: TaskHasScheduleCards :one
SELECT EXISTS (
  SELECT 1 FROM schedule_task_cards WHERE task_id = $1
)
`

func (q *Queries) TaskHasScheduleCards(ctx context.Context, taskID string) (bool, error) {
	row := q.db.QueryRow(ctx, taskHasScheduleCards, taskID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

type GetTaskByIDForRefRow struct {
	ID           string
	Title        string
	Priority     string
	PeopleNeeded int32
	Room         string
}

const getTaskByIDForRef = `-- name: GetTaskByIDForRef :one
SELECT id, title, priority, people_needed, room
FROM backlog_tasks
WHERE id = $1
`

func (q *Queries) GetTaskByIDForRef(ctx context.Context, id string) (GetTaskByIDForRefRow, error) {
	row := q.db.QueryRow(ctx, getTaskByIDForRef, id)
	var i GetTaskByIDForRefRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Priority,
		&i.PeopleNeeded,
		&i.Room,
	)
	return i, err
}
