// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Availability struct {
	ID        int32
	PersonID  string
	Date      pgtype.Date
	Status    string
	CreatedAt pgtype.Timestamptz
}

type BacklogTask struct {
	ID           string
	Title        string
	Priority     string
	PeopleNeeded int32
	Status       string
	SortOrder    int32
	CreatedAt    pgtype.Timestamptz
	AreaID       string
}

type BacklogTaskAssignment struct {
	TaskID    string
	PersonID  string
	SortOrder int32
}

type Person struct {
	ID        string
	Name      string
	Initials  string
	CreatedAt pgtype.Timestamptz
}

type PlanningWindow struct {
	ID        int32
	StartDate pgtype.Date
	EndDate   pgtype.Date
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RoomsArea struct {
	ID        string
	Name      string
	Type      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ScheduleTaskAssignment struct {
	TaskCardID int32
	PersonID   string
	SortOrder  int32
}

type ScheduleTaskCard struct {
	ID            int32
	Title         string
	Priority      string
	PeopleNeeded  int32
	SortOrder     int32
	CreatedAt     pgtype.Timestamptz
	ScheduledDate pgtype.Date
	TaskID        pgtype.Text
	Completed     bool
	AreaID        string
}

type Tool struct {
	ID        string
	Name      string
	BroughtBy pgtype.Text
	SortOrder int32
}
