// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Availability struct {
	ID        int32
	PersonID  string
	Date      pgtype.Date
	Status    string
	CreatedAt pgtype.Timestamptz
}

type Person struct {
	ID        string
	Name      string
	Initials  string
	CreatedAt pgtype.Timestamptz
}

type PlanningWindow struct {
	ID        int32
	StartDate pgtype.Date
	EndDate   pgtype.Date
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
