// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: people_availability.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllPeople = `-- name: GetAllPeople :many
SELECT id, name, initials, created_at
FROM people
ORDER BY id
`

func (q *Queries) GetAllPeople(ctx context.Context) ([]Person, error) {
	rows, err := q.db.Query(ctx, getAllPeople)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Initials,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailabilityByDateRange = `-- name: GetAvailabilityByDateRange :many
SELECT a.id, a.person_id, a.date, a.status, a.created_at
FROM availability a
WHERE a.date >= $1::date
  AND a.date <  ($1::date + $2::int * interval '1 day')
`

type GetAvailabilityByDateRangeParams struct {
	StartDate pgtype.Date
	Days      int32
}

func (q *Queries) GetAvailabilityByDateRange(ctx context.Context, arg GetAvailabilityByDateRangeParams) ([]Availability, error) {
	rows, err := q.db.Query(ctx, getAvailabilityByDateRange, arg.StartDate, arg.Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Availability
	for rows.Next() {
		var i Availability
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
