// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: people_availability.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkPersonBacklogReferences = `-- name: CheckPersonBacklogReferences :one
SELECT EXISTS (
    SELECT 1 FROM backlog_task_assignments WHERE person_id = $1
) AS has_refs
`

func (q *Queries) CheckPersonBacklogReferences(ctx context.Context, personID string) (bool, error) {
	row := q.db.QueryRow(ctx, checkPersonBacklogReferences, personID)
	var has_refs bool
	err := row.Scan(&has_refs)
	return has_refs, err
}

const checkPersonScheduleReferences = `-- name: CheckPersonScheduleReferences :one
SELECT EXISTS (
    SELECT 1 FROM schedule_task_assignments WHERE person_id = $1
) AS has_refs
`

func (q *Queries) CheckPersonScheduleReferences(ctx context.Context, personID string) (bool, error) {
	row := q.db.QueryRow(ctx, checkPersonScheduleReferences, personID)
	var has_refs bool
	err := row.Scan(&has_refs)
	return has_refs, err
}

const countPeople = `-- name: CountPeople :one
SELECT COUNT(*) FROM people
`

func (q *Queries) CountPeople(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPeople)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPerson = `-- name: CreatePerson :one
INSERT INTO people (id, name, initials)
VALUES ('p' || nextval('people_id_seq'), $1, $2)
RETURNING id
`

type CreatePersonParams struct {
	Name     string
	Initials string
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (string, error) {
	row := q.db.QueryRow(ctx, createPerson, arg.Name, arg.Initials)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteAvailability = `-- name: DeleteAvailability :exec
DELETE FROM availability
WHERE person_id = $1 AND date = $2
`

type DeleteAvailabilityParams struct {
	PersonID string
	Date     pgtype.Date
}

func (q *Queries) DeleteAvailability(ctx context.Context, arg DeleteAvailabilityParams) error {
	_, err := q.db.Exec(ctx, deleteAvailability, arg.PersonID, arg.Date)
	return err
}

const deletePerson = `-- name: DeletePerson :exec
DELETE FROM people
WHERE id = $1
`

func (q *Queries) DeletePerson(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePerson, id)
	return err
}

const getAllPeople = `-- name: GetAllPeople :many
SELECT id, name, initials, created_at
FROM people
ORDER BY id
`

func (q *Queries) GetAllPeople(ctx context.Context) ([]Person, error) {
	rows, err := q.db.Query(ctx, getAllPeople)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Initials,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailabilityByDateRange = `-- name: GetAvailabilityByDateRange :many
SELECT a.id, a.person_id, a.date, a.status, a.created_at
FROM availability a
WHERE a.date >= $1::date
  AND a.date <  ($1::date + $2::int * interval '1 day')
`

type GetAvailabilityByDateRangeParams struct {
	StartDate pgtype.Date
	Days      int32
}

func (q *Queries) GetAvailabilityByDateRange(ctx context.Context, arg GetAvailabilityByDateRangeParams) ([]Availability, error) {
	rows, err := q.db.Query(ctx, getAvailabilityByDateRange, arg.StartDate, arg.Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Availability
	for rows.Next() {
		var i Availability
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPeoplePaginated = `-- name: GetPeoplePaginated :many
SELECT id, name, initials, created_at
FROM people
ORDER BY id
LIMIT $1 OFFSET $2
`

type GetPeoplePaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetPeoplePaginated(ctx context.Context, arg GetPeoplePaginatedParams) ([]Person, error) {
	rows, err := q.db.Query(ctx, getPeoplePaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Initials,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPerson = `-- name: GetPerson :one
SELECT id, name, initials, created_at
FROM people
WHERE id = $1
`

func (q *Queries) GetPerson(ctx context.Context, id string) (Person, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Initials,
		&i.CreatedAt,
	)
	return i, err
}

const personExists = `-- name: PersonExists :one
SELECT EXISTS (
    SELECT 1 FROM people WHERE id = $1
) AS exists
`

func (q *Queries) PersonExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, personExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updatePerson = `-- name: UpdatePerson :exec
UPDATE people
SET name = $2, initials = $3
WHERE id = $1
`

type UpdatePersonParams struct {
	ID       string
	Name     string
	Initials string
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) error {
	_, err := q.db.Exec(ctx, updatePerson, arg.ID, arg.Name, arg.Initials)
	return err
}

const upsertAvailability = `-- name: UpsertAvailability :exec
INSERT INTO availability (person_id, date, status)
VALUES ($1, $2, $3)
ON CONFLICT (person_id, date)
DO UPDATE SET status = EXCLUDED.status
`

type UpsertAvailabilityParams struct {
	PersonID string
	Date     pgtype.Date
	Status   string
}

func (q *Queries) UpsertAvailability(ctx context.Context, arg UpsertAvailabilityParams) error {
	_, err := q.db.Exec(ctx, upsertAvailability, arg.PersonID, arg.Date, arg.Status)
	return err
}
