// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planning_window.sql

package db

import (
	"context"
)

const getPlanningWindow = `-- name: GetPlanningWindow :one
SELECT id, start_date, end_date, created_at, updated_at
FROM planning_windows
LIMIT 1
`

func (q *Queries) GetPlanningWindow(ctx context.Context) (PlanningWindow, error) {
	row := q.db.QueryRow(ctx, getPlanningWindow)
	var i PlanningWindow
	err := row.Scan(
		&i.ID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
