// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms_areas.sql

package db

import (
	"context"
)

const createRoom = `-- name: CreateRoom :one
WITH next_id AS (
  SELECT COALESCE(MAX(CAST(SUBSTRING(id FROM 6) AS INTEGER)), 0) + 1 AS num FROM rooms_areas
)
INSERT INTO rooms_areas (id, name, type)
SELECT 'room-' || next_id.num, $1, $2 FROM next_id
RETURNING id, name, type, created_at, updated_at
`

type CreateRoomParams struct {
	Name string
	Type string
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (RoomsArea, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.Name, arg.Type)
	var i RoomsArea
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :one
DELETE FROM rooms_areas
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteRoom(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteRoom, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, type, created_at, updated_at
FROM rooms_areas
WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id string) (RoomsArea, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i RoomsArea
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, type, created_at, updated_at
FROM rooms_areas
ORDER BY name
`

func (q *Queries) ListRooms(ctx context.Context) ([]RoomsArea, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomsArea
	for rows.Next() {
		var i RoomsArea
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms_areas
SET name = $2, type = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, name, type, created_at, updated_at
`

type UpdateRoomParams struct {
	ID   string
	Name string
	Type string
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (RoomsArea, error) {
	row := q.db.QueryRow(ctx, updateRoom, arg.ID, arg.Name, arg.Type)
	var i RoomsArea
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
