// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_backlog.sql

package db

import (
	"context"
)

const getTaskBacklog = `-- name: GetTaskBacklog :many
SELECT id, title, priority, people_needed, room, status
FROM backlog_tasks
ORDER BY sort_order
`

type GetTaskBacklogRow struct {
	ID           string
	Title        string
	Priority     string
	PeopleNeeded int32
	Room         string
	Status       string
}

func (q *Queries) GetTaskBacklog(ctx context.Context) ([]GetTaskBacklogRow, error) {
	rows, err := q.db.Query(ctx, getTaskBacklog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskBacklogRow
	for rows.Next() {
		var i GetTaskBacklogRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Priority,
			&i.PeopleNeeded,
			&i.Room,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskBacklogAssignments = `-- name: GetTaskBacklogAssignments :many
SELECT task_id, person_id
FROM backlog_task_assignments
ORDER BY task_id, sort_order
`

type GetTaskBacklogAssignmentsRow struct {
	TaskID   string
	PersonID string
}

func (q *Queries) GetTaskBacklogAssignments(ctx context.Context) ([]GetTaskBacklogAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, getTaskBacklogAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskBacklogAssignmentsRow
	for rows.Next() {
		var i GetTaskBacklogAssignmentsRow
		if err := rows.Scan(&i.TaskID, &i.PersonID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
