// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_backlog.sql

package db

import (
	"context"
)

const getTaskBacklog = `-- name: GetTaskBacklog :many
SELECT id, title, priority, people_needed, room, status
FROM backlog_tasks
ORDER BY sort_order
`

func (q *Queries) GetTaskBacklog(ctx context.Context) ([]BacklogTask, error) {
	rows, err := q.db.Query(ctx, getTaskBacklog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BacklogTask
	for rows.Next() {
		var i BacklogTask
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Priority,
			&i.PeopleNeeded,
			&i.Room,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskBacklogAssignments = `-- name: GetTaskBacklogAssignments :many
SELECT task_id, person_id
FROM backlog_task_assignments
ORDER BY task_id, sort_order
`

func (q *Queries) GetTaskBacklogAssignments(ctx context.Context) ([]BacklogTaskAssignment, error) {
	rows, err := q.db.Query(ctx, getTaskBacklogAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BacklogTaskAssignment
	for rows.Next() {
		var i BacklogTaskAssignment
		if err := rows.Scan(
			&i.TaskID,
			&i.PersonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
