// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tools.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearToolBringer = `-- name: ClearToolBringer :one
UPDATE tools
SET brought_by = NULL
WHERE id = $1
RETURNING id, name, brought_by, sort_order
`

func (q *Queries) ClearToolBringer(ctx context.Context, id string) (Tool, error) {
	row := q.db.QueryRow(ctx, clearToolBringer, id)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BroughtBy,
		&i.SortOrder,
	)
	return i, err
}

const createTool = `-- name: CreateTool :one
INSERT INTO tools (id, name, sort_order)
VALUES ('tool-' || nextval('tools_id_seq'), $1, $2)
RETURNING id, name, brought_by, sort_order
`

type CreateToolParams struct {
	Name      string
	SortOrder int32
}

func (q *Queries) CreateTool(ctx context.Context, arg CreateToolParams) (Tool, error) {
	row := q.db.QueryRow(ctx, createTool, arg.Name, arg.SortOrder)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BroughtBy,
		&i.SortOrder,
	)
	return i, err
}

const deleteTool = `-- name: DeleteTool :one
DELETE FROM tools
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteTool(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteTool, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const getMaxToolSortOrder = `-- name: GetMaxToolSortOrder :one
SELECT COALESCE(MAX(sort_order), 0)::int AS max_sort_order
FROM tools
`

func (q *Queries) GetMaxToolSortOrder(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxToolSortOrder)
	var max_sort_order int32
	err := row.Scan(&max_sort_order)
	return max_sort_order, err
}

const getToolByID = `-- name: GetToolByID :one
SELECT id, name, brought_by, sort_order
FROM tools
WHERE id = $1
`

func (q *Queries) GetToolByID(ctx context.Context, id string) (Tool, error) {
	row := q.db.QueryRow(ctx, getToolByID, id)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BroughtBy,
		&i.SortOrder,
	)
	return i, err
}

const getTools = `-- name: GetTools :many
SELECT id, name, brought_by, sort_order
FROM tools
ORDER BY sort_order
`

func (q *Queries) GetTools(ctx context.Context) ([]Tool, error) {
	rows, err := q.db.Query(ctx, getTools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tool
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BroughtBy,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setToolBringer = `-- name: SetToolBringer :one
UPDATE tools
SET brought_by = $2
WHERE id = $1
RETURNING id, name, brought_by, sort_order
`

type SetToolBringerParams struct {
	ID        string
	BroughtBy pgtype.Text
}

func (q *Queries) SetToolBringer(ctx context.Context, arg SetToolBringerParams) (Tool, error) {
	row := q.db.QueryRow(ctx, setToolBringer, arg.ID, arg.BroughtBy)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BroughtBy,
		&i.SortOrder,
	)
	return i, err
}

const updateTool = `-- name: UpdateTool :one
UPDATE tools
SET name = $2, sort_order = $3
WHERE id = $1
RETURNING id, name, brought_by, sort_order
`

type UpdateToolParams struct {
	ID        string
	Name      string
	SortOrder int32
}

func (q *Queries) UpdateTool(ctx context.Context, arg UpdateToolParams) (Tool, error) {
	row := q.db.QueryRow(ctx, updateTool, arg.ID, arg.Name, arg.SortOrder)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BroughtBy,
		&i.SortOrder,
	)
	return i, err
}
