// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions, type UseMutationOptions } from '@pinia/colada';

import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import { createPerson, deletePerson, deletePersonAvailability, getDashboardPeopleAvailability, getHello, getPlanningWindow, getTasksBacklog, type Options, updatePerson, upsertPersonAvailability } from '../sdk.gen';
import type { CreatePersonData, CreatePersonError, CreatePersonResponse, DeletePersonAvailabilityData, DeletePersonAvailabilityError, DeletePersonAvailabilityResponse, DeletePersonData, DeletePersonError, DeletePersonResponse, GetDashboardPeopleAvailabilityData, GetDashboardPeopleAvailabilityError, GetDashboardPeopleAvailabilityResponse, GetHelloData, GetHelloError, GetHelloResponse, GetPlanningWindowData, GetPlanningWindowError, GetPlanningWindowResponse, GetTasksBacklogData, GetTasksBacklogError, GetTasksBacklogResponse, UpdatePersonData, UpdatePersonError, UpdatePersonResponse, UpsertPersonAvailabilityData, UpsertPersonAvailabilityError, UpsertPersonAvailabilityResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'path'> & {
        _id: string;
        baseUrl?: _JSONValue;
        body?: _JSONValue;
        query?: _JSONValue;
        tags?: _JSONValue;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (tags) {
        params.tags = tags as unknown as _JSONValue;
    }
    if (options?.body !== undefined) {
        const normalizedBody = serializeQueryKeyValue(options.body);
        if (normalizedBody !== undefined) {
            params.body = normalizedBody;
        }
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query !== undefined) {
        const normalizedQuery = serializeQueryKeyValue(options.query);
        if (normalizedQuery !== undefined) {
            params.query = normalizedQuery;
        }
    }
    return [params];
};

export const getDashboardPeopleAvailabilityQueryKey = (options?: Options<GetDashboardPeopleAvailabilityData>) => createQueryKey('getDashboardPeopleAvailability', options);

/**
 * People availability for the dashboard
 *
 * Returns a combined payload with date-range metadata, summary counts, per-person daily availability, and a status legend. The start parameter defaults to the server-local current date; clients should pass start explicitly for timezone-correct results. availableToday counts only people whose status on selectedDate equals 'available'.
 */
export const getDashboardPeopleAvailabilityQuery = defineQueryOptions<Options<GetDashboardPeopleAvailabilityData>, GetDashboardPeopleAvailabilityResponse, GetDashboardPeopleAvailabilityError>((options?: Options<GetDashboardPeopleAvailabilityData>) => ({
    key: getDashboardPeopleAvailabilityQueryKey(options),
    query: async (context) => {
        const { data } = await getDashboardPeopleAvailability({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getHelloQueryKey = (options?: Options<GetHelloData>) => createQueryKey('getHello', options);

/**
 * Hello world
 *
 * Returns a hello-world message confirming the backend is reachable.
 */
export const getHelloQuery = defineQueryOptions<Options<GetHelloData>, GetHelloResponse, GetHelloError>((options?: Options<GetHelloData>) => ({
    key: getHelloQueryKey(options),
    query: async (context) => {
        const { data } = await getHello({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getPlanningWindowQueryKey = (options?: Options<GetPlanningWindowData>) => createQueryKey('getPlanningWindow', options);

/**
 * Global planning window
 *
 * Returns the global move range with startDate, endDate, and inclusive day count. The planning window is the canonical source of truth for the move timeline. All date-dependent views derive their rendered content from this contract.
 */
export const getPlanningWindowQuery = defineQueryOptions<Options<GetPlanningWindowData>, GetPlanningWindowResponse, GetPlanningWindowError>((options?: Options<GetPlanningWindowData>) => ({
    key: getPlanningWindowQueryKey(options),
    query: async (context) => {
        const { data } = await getPlanningWindow({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getTasksBacklogQueryKey = (options?: Options<GetTasksBacklogData>) => createQueryKey('getTasksBacklog', options);

/**
 * Task backlog data
 *
 * Returns a combined payload with derived summary counts, task backlog rows, a canonical priority legend, and a canonical task-status legend. The endpoint serves as the read-only source of truth for backlog task data used by the dashboard and /tasks route.
 */
export const getTasksBacklogQuery = defineQueryOptions<Options<GetTasksBacklogData>, GetTasksBacklogResponse, GetTasksBacklogError>((options?: Options<GetTasksBacklogData>) => ({
    key: getTasksBacklogQueryKey(options),
    query: async (context) => {
        const { data } = await getTasksBacklog({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * Create a person
 *
 * Creates a new person with a client-supplied stable ID suitable for name-derived slugs.
 */
export const createPersonMutation = (options?: Partial<Options<CreatePersonData>>): UseMutationOptions<CreatePersonResponse, Options<CreatePersonData>, CreatePersonError> => ({
    mutation: async (vars) => {
        const { data } = await createPerson({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * Delete a person
 *
 * Deletes a person. Returns 409 Conflict if the person is referenced by backlog or schedule assignments.
 */
export const deletePersonMutation = (options?: Partial<Options<DeletePersonData>>): UseMutationOptions<DeletePersonResponse, Options<DeletePersonData>, DeletePersonError> => ({
    mutation: async (vars) => {
        const { data } = await deletePerson({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * Update a person
 *
 * Updates the name and initials of an existing person.
 */
export const updatePersonMutation = (options?: Partial<Options<UpdatePersonData>>): UseMutationOptions<UpdatePersonResponse, Options<UpdatePersonData>, UpdatePersonError> => ({
    mutation: async (vars) => {
        const { data } = await updatePerson({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * Delete person availability for a date
 *
 * Deletes a single availability entry for a person on a specific date. Subsequent dashboard reads will fall back to the default-missing-availability behavior.
 */
export const deletePersonAvailabilityMutation = (options?: Partial<Options<DeletePersonAvailabilityData>>): UseMutationOptions<DeletePersonAvailabilityResponse, Options<DeletePersonAvailabilityData>, DeletePersonAvailabilityError> => ({
    mutation: async (vars) => {
        const { data } = await deletePersonAvailability({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * Upsert person availability for a date
 *
 * Creates or updates a single availability entry for a person on a specific date. The status must be one of: available, busy, partial, off. The date must be within the planning window.
 */
export const upsertPersonAvailabilityMutation = (options?: Partial<Options<UpsertPersonAvailabilityData>>): UseMutationOptions<UpsertPersonAvailabilityResponse, Options<UpsertPersonAvailabilityData>, UpsertPersonAvailabilityError> => ({
    mutation: async (vars) => {
        const { data } = await upsertPersonAvailability({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});
