// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions } from '@pinia/colada';

import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import { getDashboardPeopleAvailability, getHello, getPlanningWindow, type Options } from '../sdk.gen';
import type { GetDashboardPeopleAvailabilityData, GetDashboardPeopleAvailabilityError, GetDashboardPeopleAvailabilityResponse, GetHelloData, GetHelloError, GetHelloResponse, GetPlanningWindowData, GetPlanningWindowError, GetPlanningWindowResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'path'> & {
        _id: string;
        baseUrl?: _JSONValue;
        body?: _JSONValue;
        query?: _JSONValue;
        tags?: _JSONValue;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (tags) {
        params.tags = tags as unknown as _JSONValue;
    }
    if (options?.body !== undefined) {
        const normalizedBody = serializeQueryKeyValue(options.body);
        if (normalizedBody !== undefined) {
            params.body = normalizedBody;
        }
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query !== undefined) {
        const normalizedQuery = serializeQueryKeyValue(options.query);
        if (normalizedQuery !== undefined) {
            params.query = normalizedQuery;
        }
    }
    return [params];
};

export const getDashboardPeopleAvailabilityQueryKey = (options?: Options<GetDashboardPeopleAvailabilityData>) => createQueryKey('getDashboardPeopleAvailability', options);

/**
 * People availability for the dashboard
 *
 * Returns a combined payload with date-range metadata, summary counts, per-person daily availability, and a status legend. The start parameter defaults to the server-local current date; clients should pass start explicitly for timezone-correct results. availableToday counts only people whose status on selectedDate equals 'available'.
 */
export const getDashboardPeopleAvailabilityQuery = defineQueryOptions<Options<GetDashboardPeopleAvailabilityData>, GetDashboardPeopleAvailabilityResponse, GetDashboardPeopleAvailabilityError>((options?: Options<GetDashboardPeopleAvailabilityData>) => ({
    key: getDashboardPeopleAvailabilityQueryKey(options),
    query: async (context) => {
        const { data } = await getDashboardPeopleAvailability({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getHelloQueryKey = (options?: Options<GetHelloData>) => createQueryKey('getHello', options);

/**
 * Hello world
 *
 * Returns a hello-world message confirming the backend is reachable.
 */
export const getHelloQuery = defineQueryOptions<Options<GetHelloData>, GetHelloResponse, GetHelloError>((options?: Options<GetHelloData>) => ({
    key: getHelloQueryKey(options),
    query: async (context) => {
        const { data } = await getHello({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getPlanningWindowQueryKey = (options?: Options<GetPlanningWindowData>) => createQueryKey('getPlanningWindow', options);

/**
 * Global planning window
 *
 * Returns the global move range with startDate, endDate, and inclusive day count. The planning window is the canonical source of truth for the move timeline. All date-dependent views derive their rendered content from this contract.
 */
export const getPlanningWindowQuery = defineQueryOptions<Options<GetPlanningWindowData>, GetPlanningWindowResponse, GetPlanningWindowError>((options?: Options<GetPlanningWindowData>) => ({
    key: getPlanningWindowQueryKey(options),
    query: async (context) => {
        const { data } = await getPlanningWindow({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));
