// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions } from '@pinia/colada';

import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import { getHello, type Options } from '../sdk.gen';
import type { GetHelloData, GetHelloError, GetHelloResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'path'> & {
        _id: string;
        baseUrl?: _JSONValue;
        body?: _JSONValue;
        query?: _JSONValue;
        tags?: _JSONValue;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (tags) {
        params.tags = tags as unknown as _JSONValue;
    }
    if (options?.body !== undefined) {
        const normalizedBody = serializeQueryKeyValue(options.body);
        if (normalizedBody !== undefined) {
            params.body = normalizedBody;
        }
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query !== undefined) {
        const normalizedQuery = serializeQueryKeyValue(options.query);
        if (normalizedQuery !== undefined) {
            params.query = normalizedQuery;
        }
    }
    return [params];
};

export const getHelloQueryKey = (options?: Options<GetHelloData>) => createQueryKey('getHello', options);

/**
 * Hello world
 *
 * Returns a hello-world message confirming the backend is reachable.
 */
export const getHelloQuery = defineQueryOptions<Options<GetHelloData>, GetHelloResponse, GetHelloError>((options?: Options<GetHelloData>) => ({
    key: getHelloQueryKey(options),
    query: async (context) => {
        const { data } = await getHello({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));
